storyscript/storyscript

- CONTRIBUTING.md
Add CONTRIBUTING.md with instruction on how to contribute
Closes #1
> docs(contributing): add contribution guidelines

- .travis.yml
- tox.ini
Configure tox with py27, py36 and pep8 environments
Resolves #9
> Configure tox with py27, py36 and pep8 environments

- storyscript/__init__.py
- storyscript/resolver.py
- tests/unittests/test_resolver.py
- tox.ini
These methods are used to resolve objects in the StoryScript to their respective values from a chunk of data.
> Add object resolving methods

- setup.py
- storyscript/version.py
- tests/unittests/test_cli.py
- tests/unittests/test_version.py
Note that this also requires updating against pypi
closes #21
I bumped the version to 0.0.2
```
python setup.py install
```
And then check the storyscript version
Version bump to 0.0.2
> Update pypi version

- README.rst
Add Readthedocs badge
Added Readthedocs badge
> docs(readme): add Readthedocs badge

- docs/advanced.rst
- docs/getting-started.rst
- docs/index.rst
- docs/stories.rst
- docs/syntax.rst
- story
A number of doc updates. See diff 👍
> 📚 Documentation updates

- setup.py
- storyscript/version.py
- tests/unittests/test_cli.py
- tests/unittests/test_version.py
Version bump to 0.0.4, so that latest fixes are available when installing from pip.
PyPI needs to be updated also
> Version 0.0.4

- storyscript/resolver.py
- tests/integration/test_resolver.py
- tests/unittests/test_resolver.py
closes #51 
I refactored the resolver functions to a class with unittesting. The old test are now used as integration tests.
Refactor resolver module
> Refactor resolver module

- storyscript/resolver.py
- tests/unittests/test_resolver.py
closes #53 
Resolver.resolve can resolve string objects
Added Resolver.string and flow control in Resolver.object
Add resolution for string objects
> Resolver can resolve string objects

- storyscript/parser.py
fixes #58 
Make sure that Parser.p_string_inner calls String.add in the correct way
Parser.p_string_inner uses String.add correctly
> fix(parser): Parser.p_string_inner uses String.add correctly

- storyscript/resolver.py
- tests/unittests/test_resolver.py
Fixes strings and values (path-like) resolution
> Fix string and values resolution

- storyscript/resolver.py
- tests/integration/test_resolver.py
- tests/unittests/test_resolver.py
Resolver.resolve parses lists of objects with Resolver.lists
> Resolver.resolve parses lists

- setup.py
- storyscript/version.py
- tests/unittests/test_cli.py
- tests/unittests/test_version.py
Updates Storyscript to version 0.0.5
Version bump to 0.0.5
> Version 0.0.5

- storyscript/lexer.py
- storyscript/parser.py
- storyscript/resolver.py
- storyscript/tree/Method.py
- tests/unittests/test_objects.py
- tests/unittests/test_resolver.py
Adding support for defining objects, close #5 
Issues remain with `DEDENTS` which I could not figure out.
Also, trying a new test strategy, see [here](https://github.com/asyncy/storyscript/pull/15/files#diff-f806432afa278a6be909f33457e3d0ba).
> WIP Support for objects

- docs/syntax.rst
Added exaplanation of the wait command in the docs
> docs(syntax): explain wait syntax

- tests/unittests/tree/test_method.py
json mock returns an int to avoid infinite recursion
> tests(method): json mock returns an int to avoid infinite recursion

- docs/syntax.rst
docs(syntax): update arrays section
> docs(syntax): update arrays section

- setup.py
- storyscript/version.py
- tests/unittests/test_cli.py
- tests/unittests/test_version.py
> chore(setup): version bump to 0.0.6

- setup.py
- storyscript/version.py
- tests/unittests/test_cli.py
- tests/unittests/test_version.py
> chore(setup): version bump to 0.0.7

- storyscript/parser.py
- tests/unittests/conftest.py
- tests/unittests/test_parser.py
> Tree wait enter line

- storyscript/lexer.py
- storyscript/parser.py
- storyscript/tree/String.py
- tests/unittests/test_file.py
Special syntax structure for files via #73. This syntax used to distinguish file paths vs regular strings.
> Add syntax for files

- tests/unittests/test_comments.py
Lint comments tests so that pep8 test can pass on travis
> tests(comments): lint comments tests

- setup.py
- storyscript/version.py
- tests/unittests/test_cli.py
- tests/unittests/test_version.py
> chore(setup): version bump to 0.0.8

- setup.py
- storyscript/version.py
- tests/unittests/test_cli.py
- tests/unittests/test_version.py
> Version 0.0.9

- storyscript/resolver.py
- storyscript/version.py
- tests/unittests/test_resolver.py
- tests/unittests/test_version.py
Resolver.resolve does not try to to join boolean results
closes #97
> Fix resolver booleans

- storyscript/lexer.py
- storyscript/parser.py
Remove unused PASS token from lexer and parser
closes #105
> fix(lexer): remove unused PASS token

- storyscript/tree/Program.py
- tests/unittests/tree/test_program.py
Program.parse_item can deal with lists of items
> fix(program): Program.parse_item can parse lists of items

- storyscript/compiler.py
- storyscript/parser/grammar.py
- tests/unittests/compiler.py
- tests/unittests/parser/grammar.py
Fixes compiler assignments, objects and lists
> Fix compiler assignments

- storyscript/compiler.py
- tests/integration/parser.py
- tests/unittests/compiler.py
The compile should add line metadata needed for execution, like next, enter and exit
> WIP Compiler line metadata

- storyscript/compiler.py
- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/compiler.py
- tests/unittests/parser/grammar.py
> Remove wait syntax

- storyscript/compiler.py
- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/compiler.py
- tests/unittests/parser/grammar.py
> Remove next syntax

- storyscript/app.py
- storyscript/cli.py
- storyscript/compiler.py
- tests/unittests/compiler.py
- tests/unittests/test_app.py
- tests/unittests/test_cli.py
> Story path in json

- storyscript/app.py
- storyscript/compiler.py
- tests/unittests/compiler.py
- tests/unittests/test_app.py
Add services list to each story and globally
Closes #126
> List services in the tree

- storyscript/parser/grammar.py
- tests/unittests/parser/grammar.py
Add keywords for data types
closes #127
> Add type names

- storyscript/compiler.py
- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/compiler.py
- tests/unittests/parser/grammar.py
Remove `for` and support for multiple outputs to foreach
closes #131
> Better foreach

- storyscript/parser/grammar.py
- tests/unittests/parser/grammar.py
Improves the name token to include numbers and underscores
closes #139
> Better name token

- README.rst
Updated readme
Readme Doc URL changed from Sphinxdoc to internal
> correct URL for documentation in readme

- storyscript/compiler.py
- tests/unittests/compiler.py
> Better services tree

- README.rst
> docs(readme): replace readthedocs badge

- README.rst
Improvements to the contributing sections. Feedback welcome.
closes #167
> docs(readme): better contributing section

- README.rst
Improvements and fixes to the readme, update the examples syntax, add link to development docs
Better examples and introduction in the readme
> Better readme introduction

- storyscript/compiler.py
- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/compiler.py
- tests/unittests/parser/grammar.py
Added support for paths and values in conditionals, instead of having just the NAME token. This also fixes the compilation of expression objects for conditionals.
Added support for paths and values in conditionals
closes #177
> Conditionals paths values

- storyscript/compiler.py
- storyscript/exceptions.py
- storyscript/parser/grammar.py
- tests/unittests/compiler.py
- tests/unittests/exceptions.py
- tests/unittests/parser/grammar.py
Add syntax and compiled tree for return statements, along with errors for return statements outside functions
Add return statements
closes #169
> Return statement

- storyscript/parser/grammar.py
- storyscript/version.py
- tests/unittests/parser/grammar.py
- tests/unittests/version.py
Changed the regular expression for comments so that multiline comments are parsed correctly
Add support for multiline comments
closes #188
> Multiline comments

- storyscript/parser/parser.py
- tests/unittests/parser/parser.py
> feat(parser): Parser.parse show syntax errors

- storyscript/compiler/compiler.py
- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/compiler/compiler.py
- tests/unittests/parser/grammar.py
closes #197
Services blocks are recognized and compiled with the parent line number
Services blocks are recognized and compiled with the parent line numberquest for inclusion in the
> Service block parent

- storyscript/app.py
- storyscript/cli.py
- storyscript/compiler/__init__.py
- storyscript/compiler/compiler.py
- storyscript/compiler/lines.py
- storyscript/parser/parser.py
- storyscript/version.py
- tests/unittests/app.py
- tests/unittests/cli.py
- tests/unittests/compiler/compiler.py
- tests/unittests/compiler/lines.py
- tests/unittests/parser/parser.py
- tests/unittests/version.py
Please make sure you've read and understood our contributing guidelines;
closes #204
Pretty print all predictable errors. Added a debug mode to disable pretty printing of errors
Pretty print all predictable errors. Added a debug mode to disable pretty printing of errors
> Pretty print errors

- storyscript/compiler/compiler.py
- storyscript/compiler/lines.py
- storyscript/version.py
- tests/unittests/compiler/compiler.py
- tests/unittests/compiler/lines.py
- tests/unittests/version.py
closes #208 
Service blocks are compiled with enter attribute
Service blocks are compiled with enter attribute
> Services block missing enter

- storyscript/__init__.py
- storyscript/app.py
- storyscript/version.py
- tests/unittests/app.py
- tests/unittests/storyscript.py
- tests/unittests/version.py
closes #202 
Added JSON-like api for parsing stories
Added JSON-like api for parsing stories
> Json like api

- storyscript/compiler/compiler.py
- storyscript/compiler/lines.py
- storyscript/version.py
- tests/unittests/compiler/compiler.py
- tests/unittests/compiler/lines.py
- tests/unittests/version.py
closes #181 
Add an entrypoint property to compiled metadata
Add an entrypoint property to compiled metadata
> Mark the initial line

- .circleci/config.yml
closes #132
Switch to CircleCI
Switch to CircleCI
> chore(circle): add circleci configuration

- docs/syntax.rst
- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/parser/grammar.py
closes #209
Removed typed arguments from function output
Removed typed arguments from function output
> No typed arguments function output

- storyscript/compiler/compiler.py
- storyscript/exceptions.py
- storyscript/parser/parser.py
- storyscript/parser/transformer.py
- storyscript/version.py
- tests/unittests/compiler/compiler.py
- tests/unittests/exceptions.py
- tests/unittests/parser/parser.py
- tests/unittests/parser/transformer.py
- tests/unittests/version.py
Prettyprint UnexpectedInput errors, along with other exceptions handling improvements and fixes
Pretty print UnexpectedInput errors
> Handle unexpected input errors

- storyscript/compiler/__init__.py
- storyscript/compiler/compiler.py
- storyscript/compiler/lines.py
- storyscript/compiler/objects.py
- storyscript/compiler/preprocessor.py
- storyscript/parser/grammar.py
- storyscript/parser/tree.py
- tests/unittests/compiler/compiler.py
- tests/unittests/compiler/lines.py
- tests/unittests/compiler/preprocessor.py
- tests/unittests/parser/grammar.py
- tests/unittests/parser/tree.py
closes #130
Add support for inline expressions/embedded calls
Add support for inline expressions/embedded calls
> Inline expressions

- README.rst
> docs(readme): update circleci badge to storyscript/storyscript

- storyscript/cli.py
- tests/unittests/cli.py
closes #211 
Add version command
Add version command
> feat(cli): add version command

- storyscript/compiler/compiler.py
- storyscript/compiler/objects.py
- storyscript/parser/grammar.py
- tests/unittests/compiler/compiler.py
- tests/unittests/compiler/objects.py
- tests/unittests/parser/grammar.py
closes #237
Add support for when blocks
Add support for when blocks
> Add when syntax

- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/parser/grammar.py
closes #253 
Remove FILEPATH from the grammar
> Remove filepath from grammar

- docs/compiler.rst
- docs/syntax.rst
- storyscript/compiler/compiler.py
- storyscript/compiler/objects.py
- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/compiler/compiler.py
- tests/unittests/compiler/objects.py
- tests/unittests/conftest.py
- tests/unittests/parser/grammar.py
closes #246, closes #247, closes #251
Removes operations from the grammar in favour of more flexible expressions along with some fixes for mutations
Removes operations from the grammar in favour of more flexible expressions
> Fix operations

- docs/syntax.rst
Update the documentation with import and service+when syntax
Update the documentation with import and service+when syntax
> Add missing documentation for streams and imports

- storyscript/parser/grammar.py
- tests/unittests/parser/grammar.py
closes #262 
Add missing number type
Add missing number type
> Missing number type

- storyscript/parser/grammar.py
- tests/integration/compiler.py
- tests/unittests/parser/grammar.py
Fix else statements failing because there is no token on the line
Fix else statements failing because there is no token on the line
> Fix else statements compilation

- storyscript/parser/grammar.py
- tests/integration/compiler.py
- tests/unittests/parser/grammar.py
Allow multiline objects
Allow multiline objects
> Allow multiline objects

- setup.py
- storyscript/compiler/objects.py
- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/compiler/objects.py
- tests/unittests/parser/grammar.py
Ignore whitespaces and remove them from the grammar to simplifiy it
Ignore whitespaces and remove them from the grammar to simplifiy it
> Ignore whitespaces in the grammar

- .circleci/config.yml
- .coveragerc
- tox.ini
closes #302 
Split coverage for unit and integration tests
Split coverage for unit and integration tests
> Split coverage for unit and integration tests

- storyscript/parser/ebnf.py
- storyscript/parser/grammar.py
- tests/unittests/parser/ebnf.py
- tests/unittests/parser/grammar.py
Refactor Ebnf module to be more effective and consequently the Grammar module to work with the new Ebnf
Refactor Ebnf and Grammar modules
> Refactor ebnf

- docs/compiler.rst
- docs/syntax.rst
- storyscript/compiler/compiler.py
- storyscript/compiler/lines.py
- storyscript/parser/grammar.py
- tests/integration/compiler.py
- tests/integration/parser.py
- tests/unittests/compiler/compiler.py
- tests/unittests/compiler/lines.py
- tests/unittests/parser/grammar.py
closes #287 
Add syntax and ability to compile try, catch and finally blocks
Add syntax and ability to compile try, catch and finally blocks
> Implement try, catch and finally

- docs/compiler.rst
- docs/syntax.rst
- storyscript/compiler/objects.py
- storyscript/parser/grammar.py
- tests/integration/compiler.py
- tests/integration/parser.py
- tests/unittests/compiler/objects.py
- tests/unittests/parser/grammar.py
closes #288 
closes #252 
Implented regular expressions
Implented regular expressions
> Add regular expressions

- storyscript/parser/parser.py
- storyscript/story.py
- tests/unittests/parser/parser.py
- tests/unittests/story.py
closes #319 
Fix lex command by having Story clean the source instead of Parser
> Fix lex command

- storyscript/parser/parser.py
- tests/unittests/parser/parser.py
closes #313 
Compile empty stories by producing an empty Tree
> Compile empty stories

- storyscript/cli.py
- tests/unittests/cli.py
closes #249
Compile and lex commands have a default path set to the current working forlder
> Cwd is default path

- requirements.txt
- setup.py
- storyscript/cli.py
- tests/unittests/cli.py
closes #28 
Add help command to cli
> Cli help command

- setup.py
> chore(setup): version bump to 0.6.1

- storyscript/compiler/compiler.py
- tests/integration/compiler.py
- tests/unittests/compiler/compiler.py
closes #328
Fix assignments on mutated values being compiled with 'set' method
> Fix mutation assignment method

- storyscript/app.py
- storyscript/bundle.py
- storyscript/cli.py
- storyscript/parser/parser.py
- storyscript/story.py
- tests/unittests/app.py
- tests/unittests/bundle.py
- tests/unittests/cli.py
- tests/unittests/parser/parser.py
- tests/unittests/story.py
closes #332 
Add parse command to the cli that outputs the tree of story
> Add parse command

- storyscript/parser/ebnf.py
- storyscript/parser/grammar.py
- tests/unittests/parser/ebnf.py
- tests/unittests/parser/grammar.py
closes #334
Fix multiple indented arguments by changing the rule
> Fix multitple indented arguments

- storyscript/parser/transformer.py
- tests/integration/compiler.py
- tests/unittests/parser/transformer.py
closes #335
Fix enter in indented arguments
> Fix enter in indented arguments

- storyscript/compiler/compiler.py
- storyscript/compiler/faketree.py
- storyscript/compiler/objects.py
- storyscript/compiler/preprocessor.py
- storyscript/parser/grammar.py
- storyscript/story.py
- tests/integration/compiler.py
- tests/integration/parser.py
- tests/unittests/compiler/compiler.py
- tests/unittests/compiler/faketree.py
- tests/unittests/compiler/objects.py
- tests/unittests/compiler/preprocessor.py
- tests/unittests/parser/grammar.py
- tests/unittests/story.py
closes #333 
Implement arbitrarily long arithmetic expressions. These are split in simpler expressions, similarly to what happens with inline expressions
Implement arbitrarily long arithmetic expressions
> Arbitrarily long expressions

- storyscript/compiler/faketree.py
- storyscript/compiler/objects.py
- storyscript/compiler/preprocessor.py
- storyscript/parser/tree.py
- tests/unittests/compiler/faketree.py
- tests/unittests/compiler/objects.py
- tests/unittests/compiler/preprocessor.py
- tests/unittests/parser/tree.py
Various fixes for long expressions, allowing paths in more positions and more operators
> Fix long expressions

- storyscript/parser/grammar.py
- tests/unittests/compiler/objects.py
- tests/unittests/parser/grammar.py
closes #342 
Add missing null token to the grammar
> Fix missing null

- storyscript/api.py
- tests/unittests/api.py
closes #248 
**What I did**
Api.load and Api.loads pass debug True to Story module
> Api compiles stories in debug mode

- storyscript/compiler/compiler.py
- storyscript/compiler/lines.py
- storyscript/exceptions.py
- storyscript/parser/parser.py
- storyscript/parser/transformer.py
- storyscript/story.py
- tests/unittests/compiler/compiler.py
- tests/unittests/compiler/lines.py
- tests/unittests/exceptions.py
- tests/unittests/parser/parser.py
- tests/unittests/parser/transformer.py
- tests/unittests/story.py
closes #292 
Errors will print the path of the failed story when compiling a file
> Output story name in errors

- storyscript/exceptions/storyerror.py
- tests/unittests/exceptions/storyerror.py
Add some colours to the error output
> Colored error output

- requirements.txt
- setup.py
- storyscript/Bundle.py
- tests/unittests/Bundle.py
closes #199 
Patterns and files specified in .gitignored are ignored by the bundler
> Ignore gitignore files

- storyscript/compiler/Objects.py
- tests/integration/Compiler.py
- tests/unittests/compiler/Objects.py
closes #365
Dotted paths in string templates are compiled correctly
> String templating dots

- storyscript/parser/Grammar.py
- tests/integration/parser/Values.py
closes #370 
closes #371
Allow a negative sign before numbers
> fix negative numbers

- storyscript/parser/Grammar.py
- tests/unittests/parser/Grammar.py
closes #376
Added any to types
> feat(grammar): add any to types

- README.md
> docs(readme): update codecov link

- .circleci/config.yml
> test(circleci): try removing the dependency cache for now

- .gitignore
These files keep up appearing in my `git status`.
> chore(git): add {unittest,integration}.xml to .gitignore

- storyscript/ErrorCodes.py
- storyscript/parser/Transformer.py
- tests/unittests/ErrorCodes.py
- tests/unittests/parser/Transformer.py
Fixes https://github.com/storyscript/storyscript/issues/379
> fix(errorcodes): add keywords which are reserved for future use

- storyscript/Api.py
- storyscript/Bundle.py
- storyscript/__init__.py
- storyscript/compiler/Compiler.py
- storyscript/parser/Grammar.py
- tests/unittests/Api.py
- tests/unittests/Bundle.py
- tests/unittests/StoryScript.py
closes #436
Fix compiling and parsing without a path from the cli
Fix compiling and parsing without a path from the cli
> Fix compile and parse without path

- storyscript/compiler/Faketree.py
- tests/integration/compiler/Compiler.py
- tests/unittests/compiler/Faketree.py
closes #352 
Nested inline expression are sorted in the correct order
> Nested inline expressions order

- storyscript/parser/Grammar.py
- tests/integration/compiler/Assignments.py
- tests/integration/parser/Parser.py
- tests/unittests/parser/Grammar.py
closes #441 
closes #434
Fix the ebnf definition for expression so that mutations on numbers are parsed
> fix mutations on numbers

- storyscript/compiler/Compiler.py
- storyscript/compiler/Lines.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Lines.py
closes #455 
Outputs of a parent are now recognized in all children blocks
> Outputs are not recognized in nested blocks

- storyscript/compiler/Objects.py
- tests/integration/compiler/Compiler.py
- tests/unittests/compiler/Objects.py
closes #440
Parenthesis in an expressions are compiled correctly
Parenthesis in an expressions are compiled correctly
> Parenthesis in expressions

- storyscript/compiler/Compiler.py
- tests/unittests/compiler/Compiler.py
closes #455 
Compiler.if_block passes the parent to Compiler.subtrees which accepts a parent argument
> fix(compiler): Compiler.subtrees accepts a parent argument

- setup.py
- storyscript/Bundle.py
- tests/unittests/Bundle.py
Fixes https://github.com/storyscript/storyscript/issues/532
Replaced the delegator.py dependency with plain-old `subprocess`.
> fix(dependencies): remove delegator.py dependency

- storyscript/ErrorCodes.py
- tests/unittests/ErrorCodes.py
closes #538
The duplicated E0042 is now E0043, E0043 is instead E0044
> fix(errorcodes): fix duplicated E0042

- storyscript/ErrorCodes.py
- storyscript/Intention.py
- storyscript/exceptions/StoryError.py
- tests/unittests/ErrorCodes.py
- tests/unittests/Intention.py
- tests/unittests/exceptions/StoryError.py
closes #488 
Add a specific error for lines that end with a colon
> Add error for unnecessary colons at the end of a line

- storyscript/compiler/Compiler.py
- storyscript/compiler/Objects.py
- storyscript/parser/Grammar.py
- storyscript/parser/Transformer.py
- storyscript/parser/Tree.py
- tests/integration/compiler/Compiler.py
- tests/integration/parser/Parser.py
- tests/integration/parser/Values.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Objects.py
- tests/unittests/parser/Grammar.py
- tests/unittests/parser/Tree.py
Fixes https://github.com/storyscript/storyscript/issues/420, https://github.com/storyscript/storyscript/issues/564
- Followed-up on the generalized expression from https://github.com/storyscript/storyscript/pull/542 and used it for `if_blocks`
- Fixed a few errors in how complex nested expressions are parsed (in short: Lark's operator priority doesn't help, we need to nest expressions for precendence)
- Used a precedence similar to [Python](http://www.mathcs.emory.edu/~valerie/courses/fall10/155/resources/op_precedence.html)
- Added __a lot__ of integration tests to avoid any breakage
- Adapted the grammar for `if` and `else_if` to use `expression`
- Adapted the compiler to handle the more complex `expression` in `if`/`else_if` statements
- …
> feat(compiler): allow complex assertions in flow control statements

- tests/integration/compiler/Compiler.py
The example from https://github.com/storyscript/storyscript/issues/579 already works with master. Just adding two integration tests to ensure that it continues to work.
> test(compiler): ensure that mutations on list and objects work

- storyscript/compiler/Compiler.py
- storyscript/parser/Tree.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/parser/Tree.py
closes #597 
The compile compiles all the else if of an if block, instead of just going for the first one
> Fix missing elseifs

- tests/integration/compiler/Compiler.py
Follow-up to https://github.com/storyscript/storyscript/pull/590 (with just the tests for equals).
> test(compiler): add more tests for equals

- .circleci/config.yml
- setup.py
Still requires `$PYPI_PASSWORD` to be set at https://circleci.com/gh/storyscript/storyscript/edit#env-vars
CC @judepereira
> chore(circleci): add automated CircleCi deploys to PyPi

- storyscript/Version.py
- storyscript/compiler/Lines.py
- tests/e2e/when_enter_line_fake_assignment.json
- tests/unittests/Version.py
This should fix https://github.com/storyscript/storyscript/issues/626
> fix(tests): sort the list of services as set is instable

- storyscript/Version.py
- tests/unittests/Version.py
Fixes https://github.com/storyscript/storyscript/issues/616
> fix(Version): read the VERSION file properly from a Python Egg

- storyscript/compiler/Compiler.py
- storyscript/compiler/Objects.py
- tests/e2e/complex_assert.json
- tests/e2e/complex_assert.story
- tests/e2e/expression_is.json
- tests/e2e/expression_is.story
- tests/e2e/expression_is_if_statement.json
- tests/e2e/expression_is_if_statement.story
- tests/e2e/if_else.json
- tests/e2e/if_else.story
- tests/e2e/if_elseif.json
- tests/e2e/if_elseif.story
- tests/e2e/if_inline_expression.json
- tests/e2e/if_inline_expression.story
- tests/e2e/runner.py
- tests/e2e/service_mutation.json
- tests/e2e/service_mutation2.json
- tests/e2e/unary_not_if.json
- tests/e2e/unary_not_if.story
- tests/e2e/when_enter_line_fake_assignment.json
- tests/integration/compiler/Compiler.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Objects.py
Fixes https://github.com/storyscript/storyscript/issues/630
- Replaced `assertion` with `expression` (there's no `assertion` in the JSON output anymore)
> refactor(compiler): always use expression instead of assertion

- storyscript/compiler/Compiler.py
- storyscript/compiler/Lines.py
- tests/e2e/exit_line.json
- tests/e2e/exit_line.story
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Lines.py
Fixes https://github.com/storyscript/storyscript/issues/635
> fix(compiler): set exit for foreach and while

- storyscript/Cli.py
- tests/unittests/Cli.py
`--debug` now throws the original error
> fix(CLI): throw the original error with --debug

- storyscript/compiler/Faketree.py
- storyscript/parser/Tree.py
- tests/unittests/compiler/Faketree.py
- tests/unittests/parser/Tree.py
Use the more generic `find_first_token` in preparation for more refactoring.
> refactor(FakeTree): use find_first_token()

- storyscript/Version.py
- tests/unittests/Version.py
Fixes https://github.com/storyscript/storyscript/issues/647 with solution 1.
> fix(Version): use --tags, s.t. non annotated version will be included

- docs/command-line.rst
- docs/compiler.rst
- docs/syntax.rst
A first shot at bringing the existing documentation up-to-date.
> Improve documentation

- storyscript/ErrorCodes.py
- storyscript/compiler/Compiler.py
- storyscript/parser/Transformer.py
- tests/e2e/condensed_when.json
- tests/e2e/condensed_when.story
- tests/e2e/condensed_when_fail.error
- tests/e2e/condensed_when_fail.story
- tests/e2e/condensed_when_fail2.error
- tests/e2e/condensed_when_fail2.story
- tests/e2e/condensed_when_nested.json
- tests/e2e/condensed_when_nested.story
- tests/e2e/normal_when.json
- tests/e2e/normal_when.story
- tests/unittests/compiler/Compiler.py
Fixes https://github.com/storyscript/storyscript/issues/275
Added support for detecting the `command` automatically from the parent when no `command` has been supplied.
> feat(Compiler): add support for condensed when

- tests/e2e/while_complex_expressions.json
- tests/e2e/while_complex_expressions.story
This has been fixed in https://github.com/storyscript/storyscript/pull/659, so this PR just adds the test from https://github.com/storyscript/storyscript/issues/439.
Fixes https://github.com/storyscript/storyscript/issues/439
> tests(compiler): add test for mutations in while

- storyscript/ErrorCodes.py
- storyscript/exceptions/StoryError.py
- tests/e2e/e0053_unexpected_end_of_line.error
Fixes https://github.com/storyscript/storyscript/issues/673
> feat(exceptions): trigger a better error message when a COLON was expected

- README.md
New marketing talk to make it more clear what Storyscript really is.
> Stronger readme marketing

- storyscript/ErrorCodes.py
- storyscript/exceptions/StoryError.py
- storyscript/parser/Grammar.py
- tests/e2e/function_call_invalid1.error
- tests/e2e/regex_after_name.error
- tests/e2e/regex_after_name.story
- tests/e2e/regex_after_name2.error
- tests/e2e/regex_after_name2.story
- tests/e2e/regex_after_name3.error
- tests/e2e/regex_after_name3.story
- tests/e2e/regex_after_name4.error
- tests/e2e/regex_after_name4.story
- tests/e2e/regex_after_name5.json
- tests/e2e/regex_after_name5.story
- tests/e2e/regex_after_name6.json
- tests/e2e/regex_after_name6.story
- tests/integration/parser/grammar.lark
Fixes https://github.com/storyscript/storyscript/issues/671
> increase priority for regular expressions + improve the error message for EOL expected errors + tests

- storyscript/compiler/Compiler.py
- tests/e2e/call_function_expression_nested.json
- tests/e2e/call_function_expression_unary_complex_4.json
- tests/e2e/function_call.json
- tests/e2e/function_call_arguments.json
- tests/e2e/function_call_assignment.json
- tests/e2e/function_call_multi_args.json
- tests/e2e/function_call_nested.json
- tests/e2e/function_call_with_service.json
- tests/e2e/function_call_with_service_nested.json
- tests/e2e/function_call_zero_args.json
- tests/unittests/compiler/Compiler.py
Fixes https://github.com/storyscript/storyscript/issues/695
> fix(Compiler): use 'function' field for function calls

- storyscript/compiler/Compiler.py
- storyscript/compiler/Lines.py
- storyscript/compiler/Objects.py
- storyscript/parser/Grammar.py
- storyscript/parser/Transformer.py
- storyscript/parser/Tree.py
- tests/e2e/concise_when.json
- tests/e2e/concise_when.story
- tests/e2e/concise_when_no_args.json
- tests/e2e/concise_when_no_args.story
- tests/e2e/concise_when_no_args2.json
- tests/e2e/concise_when_no_args2.story
- tests/e2e/concise_when_no_output.json
- tests/e2e/concise_when_no_output.story
- tests/e2e/condensed_when_as.json
- tests/e2e/condensed_when_as.story
- tests/e2e/condensed_when_fail3.error
- tests/e2e/condensed_when_fail3.story
- tests/e2e/condensed_when_nested2.json
- tests/e2e/condensed_when_nested2.story
- tests/e2e/condensed_when_nested_path.json
- tests/e2e/condensed_when_nested_path.story
- tests/e2e/when_complex.json
- tests/e2e/when_complex.story
- tests/integration/parser/grammar.lark
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Objects.py
- tests/unittests/parser/Transformer.py
- tests/unittests/parser/Tree.py
Fixes https://github.com/storyscript/storyscript/issues/275
Revival of https://github.com/storyscript/storyscript/pull/667
- Introduced a `when_service` due to Lark limitation of looking ahead to resolve terminal conflicts
TODO:
> feat(Parser): support concise when and improve edge cases

- storyscript/compiler/json/Objects.py
- tests/e2e/assignments_basic.json
- tests/e2e/boolean_type.json
- tests/e2e/break.json
- tests/e2e/complex_assert.json
- tests/e2e/complex_nested_expression2.json
- tests/e2e/exit_line.json
- tests/e2e/exit_line_complex.json
- tests/e2e/mutation_expression.json
- tests/e2e/return_required4.json
- tests/e2e/return_required6.json
- tests/e2e/return_required8.json
- tests/unittests/compiler/json/Objects.py
Fixes https://github.com/storyscript/storyscript/issues/721
> feat(compiler): return boolean values as objects

- storyscript/compiler/semantics/TypeResolver.py
- storyscript/compiler/semantics/symbols/Scope.py
- tests/e2e/semantics/root_scope_app.json
- tests/e2e/semantics/root_scope_app.story
- tests/e2e/semantics/root_scope_fn_app.json
- tests/e2e/semantics/root_scope_fn_app.story
Fixes https://github.com/storyscript/storyscript/issues/733
> fix(semantics): add app by default to the root scope

- README.md
Fixes https://github.com/storyscript/storyscript/issues/710
> chore(README): mention VSCode + Atom plugins

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/TypeResolver.py
- tests/e2e/condensed_when_nested.json
- tests/e2e/condensed_when_nested_invalid.error
- tests/e2e/condensed_when_nested_invalid.story
- tests/e2e/semantics/service_block_output.error
- tests/e2e/semantics/service_block_output.story
- tests/e2e/semantics/service_block_output_invalid.error
- tests/e2e/semantics/service_block_output_invalid.story
- tests/e2e/semantics/when_output_invalid.error
- tests/e2e/semantics/when_output_invalid.story
- tests/e2e/semantics/when_output_invalid2.error
- tests/e2e/semantics/when_output_invalid2.story
Gradually extends the scope of what's covered by the semantic analysis.
> feat(semantics): improve semantic checking for service + when output blocks

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/TypeResolver.py
- tests/e2e/condensed_when_nested_path.json
- tests/e2e/condensed_when_nested_path.story
- tests/e2e/semantics/service_output_nested.json
- tests/e2e/semantics/service_output_nested.story
- tests/e2e/semantics/service_output_unique.error
- tests/e2e/semantics/service_output_unique.story
- tests/e2e/semantics/service_output_unique2.error
- tests/e2e/semantics/service_output_unique2.story
- tests/e2e/semantics/service_output_unique3.error
- tests/e2e/semantics/service_output_unique3.story
Fixes https://github.com/storyscript/storyscript/issues/665
Also, sets an implicit output whenever possible.
> feat(semantics): check the output of service calls for uniqueness

- storyscript/ErrorCodes.py
- storyscript/compiler/json/JSONCompiler.py
- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/compiler/semantics/TypeResolver.py
- storyscript/parser/Grammar.py
- storyscript/parser/Transformer.py
- tests/e2e/foreach_concat.json
- tests/e2e/foreach_concat.story
- tests/e2e/foreach_inline_service.json
- tests/e2e/foreach_inline_service.story
- tests/e2e/foreach_output_required.error
- tests/e2e/foreach_output_required.story
- tests/e2e/foreach_service.json
- tests/e2e/foreach_service.story
- tests/e2e/foreach_service2.json
- tests/e2e/foreach_service2.story
- tests/integration/parser/Parser.py
- tests/integration/parser/grammar.lark
- tests/unittests/compiler/json/Compiler.py
Fixes https://github.com/storyscript/storyscript/issues/656
> feat(compiler): let foreach accept base_expressions

- storyscript/compiler/json/JSONCompiler.py
- storyscript/compiler/json/Objects.py
- storyscript/parser/Grammar.py
- tests/e2e/mutation_expr.json
- tests/e2e/mutation_expr.story
- tests/e2e/mutation_expr2.json
- tests/e2e/mutation_expr2.story
- tests/e2e/mutation_expr_error.error
- tests/e2e/mutation_expr_error.story
- tests/integration/parser/grammar.lark
- tests/unittests/compiler/json/Compiler.py
Fixes https://github.com/storyscript/storyscript/issues/579
> feat(compiler): let mutations accept arbitrary expressions

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/TypeResolver.py
- tests/e2e/nested_service_block.error
- tests/e2e/nested_service_block.story
- tests/e2e/nested_service_block2.error
- tests/e2e/nested_service_block2.story
- tests/e2e/nested_service_block3.json
- tests/e2e/nested_service_block3.story
- tests/e2e/nested_service_block4.error
- tests/e2e/nested_service_block4.story
- tests/e2e/nested_service_block5.error
- tests/e2e/nested_service_block5.story
- tests/e2e/semantics/service_output_nested.story
- tests/e2e/when_block_extended.json
- tests/e2e/when_block_extended.story
Fixes https://github.com/storyscript/storyscript/issues/666
Fixes https://github.com/asyncy/platform-engine/issues/191
> feat(compiler): disallow nested service calls

- storyscript/parser/Transformer.py
- tests/e2e/service_indented.json
- tests/e2e/service_multiline_no_output.json
- tests/e2e/service_multiline_no_output.story
- tests/e2e/service_no_output.json
- tests/e2e/service_no_output.story
- tests/unittests/parser/Transformer.py
Fixes https://github.com/storyscript/storyscript/issues/776
> fix(transfomer): don't set implicit output for service_blocks with multi-line arguments only

- storyscript/compiler/semantics/TypeResolver.py
- tests/e2e/semantics/nested_service_calls.json
- tests/e2e/semantics/nested_service_calls.story
- tests/e2e/semantics/nested_service_calls2.json
- tests/e2e/semantics/nested_service_calls2.story
Fixes https://github.com/storyscript/storyscript/issues/806
> fix(semantics): only check for service calls with nested blocks in the e nested_service_block check

- setup.py
- storyscript/Bundle.py
- tests/unittests/Bundle.py
Fixes https://github.com/storyscript/storyscript/issues/818
> fix(bundle): don't show any git errors

- tests/e2e/var_scope_mutation.json
- tests/e2e/var_scope_mutation.story
- tests/e2e/var_scope_mutation2.json
- tests/e2e/var_scope_mutation2.story
- tests/e2e/var_scope_service.json
- tests/e2e/var_scope_service.story
- tests/e2e/var_scope_service2.json
- tests/e2e/var_scope_service2.story
Add test cases for #655.
Fixes #655
Was fixed by https://github.com/storyscript/storyscript/pull/811
> tests(compiler): add tests for variable scope of mutations

- storyscript/compiler/semantics/functions/HubMutations.py
Required for https://github.com/asyncy/platform-engine/pull/264
> feat(semantics): improve engine mutation header

- storyscript/compiler/semantics/functions/HubMutations.py
Fixes https://github.com/storyscript/storyscript/issues/836
> chore(mutations): add string trim mutation + improve replace

- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/parser/Transformer.py
- tests/e2e/arg_name_shorthand.json
- tests/e2e/arg_name_shorthand.story
- tests/e2e/arg_name_shorthand2.json
- tests/e2e/arg_name_shorthand2.story
- tests/e2e/arg_name_shorthand3.json
- tests/e2e/arg_name_shorthand3.story
- tests/e2e/arg_name_shorthand3_error.error
- tests/e2e/arg_name_shorthand3_error.story
- tests/e2e/arg_name_shorthand4.json
- tests/e2e/arg_name_shorthand4.story
- tests/e2e/arg_name_shorthand5.json
- tests/e2e/arg_name_shorthand5.story
- tests/e2e/arg_name_shorthand6.json
- tests/e2e/arg_name_shorthand6.story
- tests/e2e/arg_name_shorthand_error.error
- tests/e2e/arg_name_shorthand_error.story
- tests/e2e/arg_name_shorthand_error2.error
- tests/e2e/arg_name_shorthand_error2.story
- tests/e2e/arg_name_shorthand_error3.error
- tests/e2e/arg_name_shorthand_error3.story
- tests/e2e/arg_name_shorthand_error4.error
- tests/e2e/arg_name_shorthand_error4.story
- tests/e2e/arg_name_shorthand_error5.error
- tests/e2e/arg_name_shorthand_error5.story
- tests/e2e/arg_name_shorthand_error6.error
- tests/e2e/arg_name_shorthand_error6.story
- tests/integration/parser/Parser.py
- tests/unittests/parser/Transformer.py
Fixes https://github.com/storyscript/storyscript/issues/817
TODO:
> feat(compiler): improve handling of short-hand arguments

- storyscript/compiler/lowering/Faketree.py
- storyscript/compiler/lowering/Lowering.py
- tests/e2e/service_destructuring.json
- tests/e2e/service_destructuring.story
> fix(lowering): use base_expression for destructuring

- storyscript/ErrorCodes.py
- storyscript/exceptions/StoryError.py
- tests/e2e/indentation_error.error
- tests/e2e/indentation_error.story
- tests/e2e/indentation_error2.error
- tests/e2e/indentation_error2.story
- tests/unittests/exceptions/StoryError.py
Fixes https://github.com/storyscript/storyscript/issues/807
I still have to think more about this approach. It's far from ideal, but we don't have so many options with Lark.
> fix(storyerror): improve error message for indentation errors

- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/compiler/semantics/TypeResolver.py
- storyscript/compiler/semantics/symbols/Scope.py
- storyscript/compiler/semantics/types/Types.py
- tests/e2e/app.json
- tests/e2e/app.story
- tests/e2e/function_return_object.json
- tests/e2e/function_return_object.story
- tests/e2e/semantics/return_types.json
- tests/e2e/semantics/return_types.story
- tests/e2e/semantics/service_block_output_invalid.error
- tests/e2e/semantics/when_output_invalid.error
- tests/integration/compiler/semantics/types/Types.py
- tests/integration/compiler/semantics/types/TypesOperations.py
Required for https://github.com/storyscript/storyscript/pull/855
> refactor(rename): introduce ObjectType

- storyscript/compiler/semantics/functions/HubMutations.py
Fixes https://github.com/storyscript/storyscript/issues/853
> feat(Platform): add {starts,ends}with

- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/compiler/semantics/functions/Mutation.py
- storyscript/compiler/semantics/functions/MutationTable.py
- storyscript/compiler/semantics/types/GenericTypes.py
- tests/e2e/mutation_any_contains.json
- tests/e2e/mutation_any_contains.story
- tests/e2e/mutation_any_contains2.json
- tests/e2e/mutation_any_contains2.story
- tests/e2e/mutation_any_invalid.error
- tests/e2e/mutation_any_invalid.story
- tests/e2e/mutation_any_invalid2.error
- tests/e2e/mutation_any_invalid2.story
- tests/e2e/mutation_any_invalid3.error
- tests/e2e/mutation_any_invalid3.story
- tests/e2e/mutation_any_invalid4.error
- tests/e2e/mutation_any_invalid4.story
- tests/e2e/mutation_any_invalid5.error
- tests/e2e/mutation_any_invalid5.story
- tests/e2e/mutation_any_invalid6.error
- tests/e2e/mutation_any_invalid6.story
- tests/e2e/runner.py
- tests/unittests/compiler/semantics/types/GenericTypes.py
Fixes https://github.com/storyscript/storyscript/issues/849
>  feat(semantics): check any mutations

- storyscript/compiler/json/Objects.py
- storyscript/compiler/semantics/functions/HubMutations.py
- storyscript/parser/Grammar.py
- tests/e2e/re_more_arguments.json
- tests/e2e/re_more_arguments.story
- tests/integration/parser/Values.py
- tests/integration/parser/grammar.lark
- tests/unittests/compiler/json/Objects.py
Fixes https://github.com/storyscript/storyscript/issues/863
> fix(parser): make regexp less greedy

- storyscript/compiler/lowering/Lowering.py
- storyscript/parser/Transformer.py
- tests/unittests/parser/Transformer.py
Required for https://github.com/storyscript/storyscript/pull/844
> refactor(lowering): move shorthand arguments lowering to lowering phase

- storyscript/parser/Transformer.py
- storyscript/parser/Tree.py
- tests/e2e/service_call_arguments_multiline.json
- tests/e2e/service_call_arguments_multiline.story
- tests/unittests/parser/Transformer.py
- tests/unittests/parser/Tree.py
Fixes https://github.com/storyscript/storyscript/issues/867
Just a draft to show where the problem is. Still needs more test cases to prevent future regressions.
> fix(parser): compile inline statements for multiline arguments correctly

- storyscript/compiler/semantics/functions/HubMutations.py
`index` should return an integer.
> fix(semantics): update List index of:A header to return an int

- storyscript/compiler/lowering/Lowering.py
- tests/e2e/dot_mutation.json
- tests/e2e/dot_mutation.story
- tests/e2e/dot_mutation2.json
- tests/e2e/dot_mutation2.story
- tests/e2e/dot_mutation3.json
- tests/e2e/dot_mutation3.story
- tests/e2e/dot_mutation_invalid.error
- tests/e2e/dot_mutation_invalid.story
- tests/e2e/function_call_invalid_path.error
- tests/e2e/function_call_only_name.error
- tests/e2e/function_call_only_name2.error
- tests/e2e/function_call_only_name3.error
- tests/e2e/function_call_only_name4.error
A proposal for unifying function calls and mutations. We could make the parenthesis optional if we remove dot key access for maps (sth. which we have been discussing for quite a while anyhow).
Examples:
```coffee
my_list = [1]
a = my_list.append(item: 2).index(of: 3)
```
yields:
<details>
```json
{
"tree": {
"1": {
"method": "expression",
"ln": "1",
"name": [
"my_list"
],
"args": [
{
"$OBJECT": "list",
"items": [
{
"$OBJECT": "int",
"int": 1
}
]
}
],
"src": "my_list = [1]",
"next": "2.1"
},
"2.1": {
"method": "mutation",
"ln": "2.1",
"name": [
"__p-2.1"
],
"args": [
{
"$OBJECT": "path",
"paths": [
"my_list"
]
},
{
"$OBJECT": "mutation",
"mutation": "append",
"args": [
{
"$OBJECT": "arg",
"name": "item",
"arg": {
"$OBJECT": "int",
"int": 2
}
}
]
}
],
"next": "2.2"
},
"2.2": {
"method": …
```
> feat(lowering): support dot mutations

- storyscript/compiler/semantics/FunctionResolver.py
- storyscript/compiler/semantics/Semantics.py
- storyscript/compiler/semantics/TypeResolver.py
- storyscript/compiler/semantics/Visitors.py
- storyscript/compiler/semantics/functions/FunctionTable.py
- tests/e2e/function_semantics.json
- tests/e2e/function_semantics.story
- tests/e2e/function_semantics2.json
- tests/e2e/function_semantics2.story
Fixes https://github.com/storyscript/storyscript/issues/889
> feat(semantics): separate function symbol table building into a separate run

- storyscript/parser/Transformer.py
- tests/e2e/not_allowed/unknown.error
- tests/e2e/not_allowed/unknown.story
- tests/unittests/parser/Transformer.py
Fixes https://github.com/storyscript/storyscript/issues/861
> feat(parser): add unknown as future keyword

- tests/e2e/runner.py
- tests/e2e/update
See the individual commits for details.
> Small E2E improvements

- README.md
> Point the vscode plugin link to the marketplace.

- README.md
Reverts storyscript/storyscript#920
Can be merged once the asyncy.click link has been updated.
> Revert "Point the vscode plugin link to the marketplace."

- storyscript/Cli.py
> correct help text for compile

- storyscript/compiler/semantics/TypeResolver.py
The non-controversial part of https://github.com/storyscript/storyscript/pull/927
> refactor(semantics): move common service code in check_output

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/ReturnVisitor.py
- storyscript/exceptions/StoryError.py
- tests/e2e/explicit_cast_invalid2.error
- tests/e2e/function_return_mutation_without_type.error
- tests/e2e/function_without_return_returns_value.error
- tests/e2e/function_without_return_returns_value2.error
- tests/e2e/return_output.error
- tests/e2e/return_output.story
- tests/e2e/semantics/assignment_none.error
- tests/e2e/semantics/obj_key_none.error
- tests/e2e/type_assignment_invalid.error
- tests/e2e/type_assignment_map_list.error
Fixes https://github.com/storyscript/storyscript/issues/915
>  feat(semantics): improve error message for a return with function signature mismatch

- storyscript/compiler/lowering/Lowering.py
- tests/e2e/builtin_mutation_multiple.json
- tests/e2e/builtin_mutation_multiple.story
- tests/e2e/builtin_mutation_multiple2.json
- tests/e2e/builtin_mutation_multiple2.story
- tests/e2e/builtin_mutation_multiple3.error
- tests/e2e/builtin_mutation_multiple3.story
- tests/e2e/builtin_mutation_multiple4.json
- tests/e2e/builtin_mutation_multiple4.story
- tests/e2e/dot_mutation_invalid.error
Fixes https://github.com/storyscript/storyscript/issues/923
> fix(lowering): lower multi-property mutation properly

- storyscript/compiler/semantics/TypeResolver.py
- storyscript/compiler/semantics/symbols/Scope.py
- tests/e2e/scope_individual_if_else.error
- tests/e2e/scope_individual_if_else.json
- tests/e2e/scope_individual_if_elseif_else_fail.error
- tests/e2e/scope_individual_if_elseif_else_fail.json
- tests/e2e/semantics/if_scope_joint.json
- tests/e2e/semantics/if_scope_joint.story
- tests/e2e/semantics/if_scope_joint2.json
- tests/e2e/semantics/if_scope_joint2.story
- tests/e2e/semantics/if_scope_joint3.error
- tests/e2e/semantics/if_scope_joint3.story
- tests/e2e/semantics/if_scope_joint4.error
- tests/e2e/semantics/if_scope_joint4.story
- tests/e2e/semantics/if_scope_joint5.error
- tests/e2e/semantics/if_scope_joint5.story
- tests/e2e/semantics/if_scope_joint6.error
- tests/e2e/semantics/if_scope_joint6.story
- tests/e2e/semantics/if_scope_joint7.error
- tests/e2e/semantics/if_scope_joint7.story
- tests/e2e/semantics/if_scope_joint8.json
- tests/e2e/semantics/if_scope_joint8.story
Fixes https://github.com/storyscript/storyscript/issues/925
> feat(semantics): improve scope management for if/else

- storyscript/compiler/lowering/Lowering.py
- tests/e2e/inline_expression_expansion.json
- tests/e2e/inline_expression_expansion.story
Fixes https://github.com/storyscript/storyscript/issues/916
> fix(Lowering): lower children before lowering nested_blocks

- storyscript/compiler/lowering/Lowering.py
- storyscript/parser/Grammar.py
- tests/e2e/builtin_mutation_multiple5.json
- tests/e2e/builtin_mutation_multiple5.story
- tests/e2e/builtin_mutation_multiple6.json
- tests/e2e/builtin_mutation_multiple6.story
- tests/e2e/builtin_mutation_multiple7.json
- tests/e2e/builtin_mutation_multiple7.story
- tests/integration/parser/grammar.lark
Fixes https://github.com/storyscript/storyscript/issues/933, https://github.com/storyscript/storyscript/issues/924
> feat(parser): mutation for inline function calls

- tests/e2e/builtin_mutation_multiple8.json
- tests/e2e/builtin_mutation_multiple8.story
Fixes https://github.com/storyscript/storyscript/issues/924
> tests(syntax): add test for issue 924

- storyscript/compiler/semantics/ReturnVisitor.py
- tests/e2e/ice950.error
- tests/e2e/ice950.story
Fix https://github.com/storyscript/storyscript/issues/950
> fix(semantics): ensure to have a line number for return errors

- storyscript/compiler/semantics/functions/HubMutations.py
- tests/e2e/mutation_contains.json
- tests/e2e/mutation_contains.story
- tests/e2e/semantics/mutation/invalid_arg_type.error
- tests/e2e/semantics/mutation/list_contains_err2.error
Fixes https://github.com/storyscript/storyscript/issues/960
> fix(semantics): list contains should return boolean

- tests/e2e/division_fn.json
- tests/e2e/division_fn.story
Fixes https://github.com/storyscript/storyscript/issues/966 (or at least adds a test for it as it was working in 0.20.1 too).
> chore(tests): add a test for #966

- storyscript/Story.py
- storyscript/compiler/lowering/Lowering.py
- storyscript/parser/Grammar.py
- storyscript/parser/Parser.py
- storyscript/parser/Transformer.py
- tests/e2e/not_allowed/single_quotes.error
- tests/e2e/string_templates_single_quotes.json
- tests/e2e/string_templates_single_quotes.story
- tests/integration/parser/Parser.py
- tests/integration/parser/Values.py
- tests/integration/parser/grammar.lark
- tests/unittests/Story.py
- tests/unittests/parser/Parser.py
Fixes https://github.com/storyscript/storyscript/issues/991
Scheduled for 0.21.1
> feat(parser): allow single string quotes in string templates

- storyscript/compiler/lowering/Lowering.py
- storyscript/compiler/semantics/ReturnVisitor.py
- storyscript/parser/Tree.py
- tests/e2e/function_without_return_returns_value3.error
- tests/e2e/function_without_return_returns_value3.story
Alternative to https://github.com/storyscript/storyscript/pull/987 which fixes the underlying problem of tokens being created without a valid line number
> fix(lowering): make sure that all inserted tokens have a line

- README.md
- move editor plugins up
- link to the Storyscript Cloud quickstart guide
> Link to Quickstart guide

- storyscript/compiler/json/JSONCompiler.py
- storyscript/compiler/json/JSONExpressionVisitor.py
- storyscript/compiler/json/Objects.py
- storyscript/compiler/lowering/Faketree.py
- storyscript/compiler/lowering/Lowering.py
- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/compiler/visitors/ExpressionVisitor.py
- storyscript/parser/Grammar.py
- storyscript/parser/Transformer.py
- tests/e2e/return_complex_expression_2.error
- tests/e2e/string_templates_assignments.json
- tests/e2e/string_templates_assignments2.json
- tests/e2e/string_templates_complicated_concat.json
- tests/e2e/string_templates_complicated_concat.story
- tests/e2e/string_templates_complicated_concatb.error
- tests/e2e/string_templates_complicated_concatb.story
- tests/integration/Cli.py
- tests/integration/parser/Parser.py
- tests/integration/parser/Values.py
- tests/integration/parser/grammar.lark
- tests/unittests/compiler/json/Compiler.py
- tests/unittests/compiler/visitors/ExpressionVisitor.py
Required for https://github.com/storyscript/storyscript/pull/985 and in general will working with the AST a lot easier.
> refactor(parser): reduce nested expression nodes into one

- docs/syntax.rst
- storyscript/compiler/semantics/functions/HubMutations.py
- tests/e2e/if_with_mutation.json
- tests/e2e/if_with_mutation.story
- tests/e2e/while_with_mutation.json
- tests/e2e/while_with_mutation.story
- tests/unittests/compiler/semantics/functions/HubMutations.py
See https://github.com/storyscript/platform-engine/pull/375#issuecomment-510046423
> Change mutations to camelCase, add approxEqual

- setup.py
- storyscript/__init__.py
- storyscript/compiler/semantics/functions/HubMutations.py
First part of https://github.com/storyscript/storyscript/issues/1006
Depends on https://github.com/storyscript/hub-sdk-python/pull/13
> feat(compiler): load builtins from the hub-sdk

- storyscript/ErrorCodes.py
- storyscript/compiler/json/JSONCompiler.py
- storyscript/parser/Grammar.py
- tests/e2e/continue.json
- tests/e2e/continue.story
- tests/e2e/continue_outside.error
- tests/e2e/continue_outside.story
- tests/integration/parser/grammar.lark
Fix https://github.com/storyscript/storyscript/issues/786
TODO: https://github.com/storyscript/storyscript/issues/1007
> feat(parser): add continue statement

- README.md
Bumped into a broken link, fixed it
nano, git push :)
Click the link?
Fixed Quick Start link in README
> docs: fix docs link in README

- storyscript/compiler/semantics/TypeResolver.py
- tests/e2e/semantics/service_arguments.error
- tests/e2e/semantics/service_arguments.story
- tests/e2e/while_complex_expressions.json
- tests/e2e/while_complex_expressions.story
Fixes https://github.com/storyscript/storyscript/issues/1025
Should soon be more complex once service definitions are integrated and compared against.
>  fix(TypeResolver): resolve service arguments

- setup.py
see also: https://github.com/storyscript/hub-sdk-python/pull/16
> chore(setup.py): use any patch release of story-hub

- storyscript/compiler/semantics/TypeResolver.py
- tests/e2e/service_call_as_output.error
- tests/e2e/service_call_as_output.story
- tests/e2e/service_call_as_output2.error
- tests/e2e/service_call_as_output2.story
- tests/e2e/service_call_as_output3.error
- tests/e2e/service_call_as_output3.story
- tests/e2e/service_call_as_output4.error
- tests/e2e/service_call_as_output4.story
Fixes https://github.com/storyscript/storyscript/issues/1051
> fix(semantics): Check service calls without assignment for output definition

- setup.py
- storyscript/__init__.py
- storyscript/compiler/semantics/functions/HubMutations.py
Upgrade story-hub to 0.1.0, which changes the root package name since the automatic brew release update can't handle two top level packages named `storyscript`.
> Upgrade story-hub to 0.1.0.

- storyscript/Bundle.py
- tests/unittests/Bundle.py
Follow-up for https://github.com/storyscript/storyscript/pull/1061
> chore(Bundle): graceful fail for 'git ls-files' errors

- .circleci/config.yml
- scripts/merge_stable
- scripts/pr_send
Fixes part of https://github.com/storyscript/storyscript/issues/1068
- for every PR to `stable` -> will automatically open a PR with the bug fix to master
- allows running `merge_stable` locally (when there's a merge conflict) as well
TODO:
> chore(CI): auto-create merge_stable PR

- .circleci/config.yml
- scripts/bump_versions
- second part of https://github.com/storyscript/storyscript/issues/1068
- only for the CLI for now (once this is working -> other repos will be added too)
Example: https://github.com/storyscript/cli/pull/257
> chore(CI): automatically send an update PR to the CLI

- .circleci/config.yml
- scripts/bump_versions
A few small fixes for  https://github.com/storyscript/storyscript/pull/1085
The CircleCi filter is required to trigger the job.
> chore(CI): update PRs - add CircleCi filter

- RELEASING.md
Final part of https://github.com/storyscript/storyscript/issues/1068
CC @judepereira
> docs(release): add releasing guide

- setup.py
Update bom-open from 0.3.6 to 0.4.0,
notably fixing a bug with opening empty files.
> chore(dependencies): Update bom-open from 0.3.6 to 0.4.0

- setup.py
Update lark library to 0.7.2,
includes performance improvement.
> chore(dependencies): Upgrade lark to 0.7.2

- storyscript/compiler/semantics/TypeResolver.py
- tests/e2e/semantics/functions_global_scope.json
- tests/e2e/semantics/functions_global_scope.story
Fixes https://github.com/storyscript/storyscript/issues/1120
Access to global state for functions was disabled on purpose as functions must be weakly pure in order for the user to reason better about his code, avoid side effects etc, allow function replay etc.
However, now that all global state is readonly, we can allow this in the next release.
> feat(semantics): allow access to global state for functions

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/TypeResolver.py
- storyscript/exceptions/CompilerError.py
- storyscript/exceptions/__init__.py
- tests/e2e/semantics/output_assignment_existing_var.error
- tests/e2e/semantics/output_assignment_existing_var.story
- tests/e2e/semantics/output_assignment_existing_var2.error
- tests/e2e/semantics/output_assignment_existing_var2.story
- tests/e2e/semantics/output_assignment_existing_var3.error
- tests/e2e/semantics/output_assignment_existing_var3.story
- tests/e2e/semantics/output_assignment_existing_var4.error
- tests/e2e/semantics/output_assignment_existing_var4.story
- tests/e2e/semantics/output_assignment_existing_var5.error
- tests/e2e/semantics/output_assignment_existing_var5.story
- tests/e2e/semantics/output_assignment_existing_var6.error
- tests/e2e/semantics/output_assignment_existing_var6.story
Fixes https://github.com/storyscript/storyscript/issues/1122
> fix(TypeResolver): Output assignment should error when it would overload an existing variable

- storyscript/Bundle.py
- storyscript/Cli.py
- tests/integration/Api.py
- tests/integration/Cli.py
- tests/unittests/Bundle.py
- tests/unittests/Cli.py
Fixes https://github.com/storyscript/storyscript/issues/1121
> fix(Bundle): report story name in errors when working on multiple stories

- storyscript/App.py
- storyscript/Bundle.py
- storyscript/Cli.py
- storyscript/Story.py
- storyscript/compiler/pretty/Objects.py
- storyscript/compiler/pretty/PrettyExpressionVisitor.py
- storyscript/compiler/pretty/PrettyPrinter.py
- storyscript/parser/Transformer.py
- tests/integration/Cli.py
- tests/integration/compiler/pretty/PrettyPrinter.py
- tests/unittests/Cli.py
- tests/unittests/Story.py
Fixes https://github.com/storyscript/storyscript/issues/751
Required for e.g. "Format" in SLS, better error messages and debug output.
TODO:
More TODO:
- `--inline` | `-i` CLI option (https://github.com/storyscript/storyscript/issues/1138)
- mutation (https://github.com/storyscript/storyscript/issues/1136)
- Expose AST formatting for semantics (https://github.com/storyscript/storyscript/issues/1137)
> feat(compiler): add AST pretty printer

- storyscript/App.py
- storyscript/Cli.py
- tests/integration/Cli.py
- tests/unittests/Cli.py
Fixes https://github.com/storyscript/storyscript/issues/1138
> feat(CLI): allow inline formatting

- storyscript/parser/Transformer.py
- tests/integration/compiler/pretty/PrettyPrinter.py
Fixes https://github.com/storyscript/storyscript/issues/1136
> fix(Transformer): fix AST transformation for value mutations with multiple arguments

- storyscript/Bundle.py
- storyscript/compiler/Compiler.py
- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/compiler/semantics/FunctionResolver.py
- storyscript/compiler/semantics/Module.py
- storyscript/compiler/semantics/ReturnVisitor.py
- storyscript/compiler/semantics/Semantics.py
- storyscript/compiler/semantics/TypeResolver.py
- storyscript/compiler/semantics/Visitors.py
- tests/e2e/runner.py
- tests/e2e/update
- tests/integration/compiler/Compiler.py
- tests/integration/compiler/Functions.py
- tests/unittests/Bundle.py
- tests/unittests/compiler/Compiler.py
Fixes https://github.com/storyscript/storyscript/issues/1118
This will allow accessing the semantic information from e.g. SLS and also make it easier for the components of semantics to access their shared functionality.
> refactor(semantics): introduce Module object + return it from compilation

- tests/e2e/ice_1066.json
- tests/e2e/ice_1066.story
Fixes https://github.com/storyscript/storyscript/issues/1066
(adds just a test case as the ICE has already been fixed in the meantime)
> test(ICE): Add test case for ICE 1066

- setup.py
- tests/e2e/semantics/mutation/obj_pop_key.error
Contains https://github.com/storyscript/hub-sdk-python/pull/29 and https://github.com/storyscript/hub-sdk-python/pull/28
> feat(hub-sdk): upgrade to 0.1.3

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/ServiceTyping.py
- tests/e2e/service_action_without_output.error
- tests/e2e/service_action_without_output.story
Fixes https://github.com/storyscript/storyscript/issues/1169
> fix(ServiceTyping): reject actions on service objects

- tests/e2e/arg_name_shorthand3.json
- tests/e2e/arg_name_shorthand3.story
- tests/e2e/foreach_concat.json
- tests/e2e/foreach_concat.story
- tests/e2e/foreach_inline_service.json
- tests/e2e/foreach_inline_service.story
- tests/e2e/foreach_service.json
- tests/e2e/foreach_service.story
- tests/e2e/function_call_three_inline_exprs.json
- tests/e2e/function_call_three_inline_exprs.story
- tests/e2e/function_call_with_service.json
- tests/e2e/function_call_with_service.story
- tests/e2e/service_inline_expression_nested.json
- tests/e2e/service_inline_expression_nested.story
- tests/e2e/update
- tests/fixtures/hub_fixture.json.fixed
mailgun service got updated on the hub and as a result doing `tests/e2e/update -a` started to break up.
This PR updates the fixtures data for the hub and fixes the tests accordingly.
EDIT: `update` tool wasn't really breaking up but started to generate error files since another param in the mailgun was marked as `required` and all the tests that weren't using it started to break. Therefore the error files were being generated with the said required field error
> chore(fixtures): update hub fixtures data and tests accordingly

- setup.py
Includes https://github.com/storyscript/hub-sdk-python/pull/42
> chore(setup.py): upgrade hub-sdk to 0.1.6

- setup.py
Includes https://github.com/storyscript/hub-sdk-python/pull/45
> chore(setup.py): upgrade hub-sdk to 0.1.7

- .travis.yml
- setup.py
- tests/unittests/Bundle.py
Fixes https://github.com/storyscript/storyscript/issues/1037
> feat(CI): Add Windows testing

- README.md
https://github.com/storyscript/.github/blob/master/CODE_OF_CONDUCT.md
> Add Code of Conduct shield + remove outdated devdocs

- setup.py
This flag was incorrectly set at the time, and is still
incorrect.
Fixes https://github.com/storyscript/storyscript/issues/1267
> Packaging fixes

- storyscript/compiler/json/JSONCompiler.py
- tests/e2e/rewrite_service_path.json
- tests/e2e/semantics/nested_service_calls.json
- tests/e2e/service_list_when.json
- tests/e2e/service_list_when.story
- tests/e2e/service_with_assignments.json
Fixes https://github.com/storyscript/storyscript/issues/1271
> fix(JSONCompiler): fix service list in payload

- storyscript/compiler/semantics/types/Types.py
- tests/e2e/implicit_to_1273.json
- tests/e2e/implicit_to_1273.story
- tests/e2e/implicit_to_list_any.json
- tests/e2e/implicit_to_list_any.story
- tests/e2e/implicit_to_list_any_nested.json
- tests/e2e/implicit_to_list_any_nested.story
- tests/e2e/implicit_to_map_any.json
- tests/e2e/implicit_to_map_any.story
Fixes https://github.com/storyscript/storyscript/issues/1273
> fix(semantics): implicit_to for any types

- storyscript/hub/TypeMappings.py
- tests/e2e/service_output_none.json
- tests/e2e/service_output_none.story
- tests/fixtures/hub_fixture.json.fixed
- tests/fixtures/update_services_fixtures
e.g.  https://github.com/omg-services/redis/blob/master/microservice.yml#L30
> fix(HubTypings): add support for output with type:none

- storyscript/compiler/semantics/symbols/Symbols.py
- tests/e2e/semantics/dot_index_object.error
- tests/e2e/semantics/dot_index_object.story
- tests/e2e/semantics/dot_index_object2.error
- tests/e2e/semantics/dot_index_object2.story
> fix(Symbols): error on indexing (action) object

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/FunctionResolver.py
- tests/e2e/object_assign_null4.error
- tests/e2e/semantics/arg_type_no_object.error
- tests/e2e/semantics/arg_type_no_object.story
- tests/e2e/semantics/arg_type_no_object2.error
- tests/e2e/semantics/arg_type_no_object2.story
> chore(Functions): ban argument with Object types for now

- setup.py
- storyscript/compiler/semantics/functions/Function.py
- storyscript/compiler/semantics/functions/HubMutations.py
- storyscript/compiler/semantics/functions/Mutation.py
- storyscript/compiler/semantics/functions/MutationBuilder.py
- storyscript/compiler/semantics/symbols/Symbols.py
- tests/integration/compiler/Compiler.py
- tests/integration/compiler/semantics/functions/MutationTable.py
- tests/unittests/compiler/semantics/functions/Function.py
- tests/unittests/compiler/semantics/functions/HubMutations.py
- tests/unittests/compiler/semantics/functions/MutationBuilder.py
- tests/unittests/compiler/semantics/symbols/Symbols.py
In preparation for storyscript/sls#94
> Use more detailed objects for builtins

- storyscript/Api.py
- storyscript/Story.py
- storyscript/compiler/semantics/Semantics.py
- storyscript/compiler/semantics/ServiceTyping.py
- tests/integration/Api.py
- tests/unittests/Api.py
- tests/unittests/Story.py
This allows SLS to inject a custom hub instance.
> feat(API): allow injecting a custom hub

- storyscript/compiler/semantics/symbols/Scope.py
- storyscript/hub/TypeMappings.py
Required for https://github.com/storyscript/sls/issues/157
> Expose properties as symbols + add description for 'app'

- storyscript/exceptions/ErrorTextFormatter.py
- tests/unittests/exceptions/StoryError.py
Required for https://github.com/storyscript/sls/issues/214
> feat(errors): expose {start,end}_column in error messages

- storyscript/Version.py
- tests/unittests/Version.py
https://github.com/storyscript/storyscript/pull/1338 for [stable]
> [stable] Merge pull request #1338 from wilzbach/version-name

- storyscript/compiler/semantics/types/Types.py
- tests/e2e/semantics/implicit_cast_list_any.json
- tests/e2e/semantics/implicit_cast_list_any.story
- tests/e2e/semantics/implicit_cast_list_any2.json
- tests/e2e/semantics/implicit_cast_list_any2.story
- tests/e2e/semantics/implicit_cast_list_any3.json
- tests/e2e/semantics/implicit_cast_list_any3.story
- tests/e2e/semantics/implicit_cast_list_any4.json
- tests/e2e/semantics/implicit_cast_list_any4.story
- tests/e2e/semantics/implicit_cast_map_any.json
- tests/e2e/semantics/implicit_cast_map_any.story
- tests/e2e/semantics/implicit_cast_map_any2.json
- tests/e2e/semantics/implicit_cast_map_any2.story
- tests/e2e/semantics/implicit_cast_map_any3.json
- tests/e2e/semantics/implicit_cast_map_any3.story
- tests/e2e/semantics/implicit_cast_map_any4.json
- tests/e2e/semantics/implicit_cast_map_any4.story
> fix(Types): allow nested type cast for map/list to any

- storyscript/compiler/pretty/PrettyPrinter.py
- tests/integration/compiler/pretty/PrettyPrinter.py
> Fix formatting object destructuring assignment
