storyscript/storyscript

- storyscript/lexer.py
- storyscript/parser.py
- tests/unittests/test_lexer.py
- tests/unittests/test_parser.py
- tox.ini
closes #29
Yacc and lex use the current working directory, instead of a directory inferred from the python file itself. This is ensures that the output directory always exists.
Changed the outputdir argument to use os.getcwd
Lexer and parser use the current working directory as output directory for Yacc
> Parser directory error

- storyscript/cli.py
- tests/unittests/test_cli.py
fixes #27 
cli.parse now calls click.style with fg instead of click.echo
Parse a story will output a green success message
cli.parse passes fg keyword to click.style instead of click.echo
> fix(cli): cli.parse passes fg keyword to click.style instead of click.echo

- storyscript/resolver.py
- tests/integration/test_resolver.py
- tests/unittests/test_resolver.py
fixes #55 
Resolver.path and Resolver.object expect 'paths' in path objects
I changed the path object format expected by Resolver
Resolver.path and Resolver.object expect 'paths' in path objects
> Resolver.path and Resolver.object expect 'paths' in path objects

- storyscript/lexer.py
- storyscript/parser.py
- storyscript/tree/Comparison.py
- storyscript/tree/Condition.py
- storyscript/tree/Expression.py
- storyscript/tree/Method.py
- storyscript/tree/Path.py
- storyscript/tree/Program.py
- storyscript/tree/String.py
- tests/unittests/test_lexer.py
- tests/unittests/test_parser.py
- tests/unittests/tree/test_comparison.py
- tests/unittests/tree/test_condition.py
- tests/unittests/tree/test_expression.py
- tests/unittests/tree/test_method.py
- tests/unittests/tree/test_path.py
- tests/unittests/tree/test_program.py
- tests/unittests/tree/test_string.py
Add support for list iterating loops, so that 
closes #64 
```
for item in list
```
is valid Storyscript
Storyscript supports for keyword in list iteration
> Support list looping

- storyscript/lexer.py
- storyscript/parser.py
- storyscript/resolver.py
- storyscript/tree/Method.py
- tests/unittests/test_list.py
- tests/unittests/test_resolver.py
- tests/unittests/tree/test_method.py
Added syntax for list definitions, closes #4 
@Vesuvium can you help fix the tests that I marked as skipped. They loop forever because of [this line](https://github.com/asyncy/storyscript/compare/syntax/list?expand=1#diff-89bca5351b491d6e0b08871700fe6033R25)
> Additionally
> - Moved `RBRACKET` to `RBRACE`
> - Moved `object` to under `variable`
> Add syntax to define lists

- storyscript/parser.py
- tests/unittests/test_conj.py
- tests/unittests/test_run.py
- tests/unittests/test_set.py
> Removing reserved and required position for arg@1 when running a container.
We have found that there are containers that do not require a start command and the container entrypoint should be used. Therefore, removing the required arg@1 as a reserved slot. The result in stories compile in the following way:
```sh
container arg1 arg2
```
```diff
- {"args": ['arg1', {'$OBJECT': 'path', 'paths': ['arg2']}]}
+ {"args": [{'$OBJECT': 'path', 'paths': ['arg1']}, {'$OBJECT': 'path', 'paths': ['arg2']}]}
```
This allows for calling containers like this:
```sh
res = count_letters "hello world"
```
> Note how arg@1 is a string.
```json
{
"args": [
{"$OJBECT": "string", "string": "hello world"}
]
}
```
----
@Vesuvium the engine needs to take into account that arg@1 is an `$OBJECT` that **may** need …
> Container first argument fix

- storyscript/parser.py
- tests/unittests/test_parser.py
Syntax tree of for statements has an enter line
fixes #92
> fix(parser): Parser.p_stmt_for_item_in_list sets the enter line

- storyscript/compiler.py
- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/compiler.py
- tests/unittests/parser/grammar.py
Add support for defining services output names.
For example, the following:
```coffee
container stream as request, response
```
will have request and response set in the output property:
```coffee
"output": [
"request",
"response"
]
```
closes #123
> Services output

- storyscript/compiler.py
- tests/unittests/compiler.py
fix(compiler): Compiler.output checks whether the tree is None
> fix(compiler): Compiler.output checks whether the tree is None

- storyscript/cli.py
- tests/unittests/cli.py
Added ability to include output file with second, optional command line argument for parse
Please see tests. You may also manually test the CLI
Add ability to output parse tree to file as second argument to "parse" command in CLI
> Output argument in CLI

- storyscript/compiler/compiler.py
- storyscript/version.py
- tests/unittests/compiler/compiler.py
- tests/unittests/version.py
closes #203 
The compiler takes note of outputs and checks them before adding a service name to the service list
Don't show services output in services list
> Services output in services list

- storyscript/parser/grammar.py
- tests/unittests/parser/grammar.py
Add support for multiline lists
Add support for multiline lists
> feat(grammar): Grammar.list recognizes multiline lists

- storyscript/compiler/compiler.py
- storyscript/parser/tree.py
- tests/unittests/compiler/compiler.py
- tests/unittests/parser/tree.py
closes #166 
The tree module exposes tree nodes through properties
Improvements to the compiler handling of parents
The tree module exposes tree nodes through properties
> Tree nodes attributes

- docs/syntax.rst
- storyscript/parser/grammar.py
- tests/integration/parser.py
- tests/unittests/parser/grammar.py
closes #217 
Functions output use "returns" instead of "->"
Functions output use "returns" instead of "->"
> Function output returns

- storyscript/parser/grammar.py
- tests/unittests/parser/grammar.py
closes #267, closes #268
Objects support paths as values and allow whitespace after column and  comma
Objects support paths as values and allow whitespace after column and  comma
> Paths and whitespaces in objects

- storyscript/story.py
- tests/unittests/story.py
closes #277 
Imports declared without '.story' are compiled correctly
Imports declared without '.story' are compiled correctly
> fix(story): Story.modules appends '.story' when missing

- storyscript/parser/grammar.py
- tests/unittests/parser/grammar.py
closes #273
Allow whitespace between column and value in services
Allow whitespace between column and value in services
>  Spaces between an arg name and an inline expression

- docs/compiler.rst
- storyscript/compiler/compiler.py
- storyscript/compiler/lines.py
- storyscript/compiler/objects.py
- storyscript/compiler/preprocessor.py
- tests/unittests/compiler/compiler.py
- tests/unittests/compiler/lines.py
- tests/unittests/compiler/objects.py
- tests/unittests/compiler/preprocessor.py
closes #274 
The compiler now registers used variables and checks that whether a service tree is a mutation on a variable or a regular service call
> Mutations miscompiled as services

- storyscript/compiler/objects.py
- tests/unittests/compiler/objects.py
closes #296
Key access paths are compiled as string objects
Key access paths are compiled as string objects
> Differentiate dot paths from key access paths

- storyscript/compiler/objects.py
- storyscript/parser/grammar.py
- tests/integration/compiler.py
- tests/integration/parser.py
- tests/unittests/compiler/objects.py
- tests/unittests/parser/grammar.py
closes #298 
Fix empty list compilation by setting Grammar.list to not drop inlined tokens
Fix empty list compilation
> Fix return empty list

- storyscript/Story.py
- tests/integration/Story.py
- tests/unittests/Story.py
closes #369 
Change the regular expression that strips comments to a backtracking-free one
> Fix multiline comments

- .circleci/config.yml
- README.md
To avoid showing a failed status badge if any PR is currently failing as by default it takes the latest build.
> docs(README): update circleci badge to use the master branch only

- tests/unittests/parser/Transformer.py
I removed while from future keywords tests in Transformer.py.
> tests(transformer): remove while from future keywords tests

- README.md
Changed instructions from `storyscript parse` to `storyscript compile` in README.md
Did not create a new issue as I feel the change is trivial and I believe this was a type (parse does not even have a -j option)
> docs(README): fix error in getting started instructions

- storyscript/ErrorCodes.py
- storyscript/compiler/Compiler.py
- storyscript/parser/Grammar.py
- storyscript/parser/Transformer.py
- tests/integration/Exceptions.py
- tests/integration/compiler/Compiler.py
- tests/integration/parser/Parser.py
- tests/unittests/ErrorCodes.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/parser/Grammar.py
- tests/unittests/parser/Transformer.py
Closes #393
Add `raise` statement to the grammar, transformer (with error codes) and compiler.
The compiler will also check whether `raise` is inside of a `catch` block and if not throw a special error (`raise_outside`).
Add `raise` statement to the Storyscript syntax.
---
> Add raise to syntax

- storyscript/Api.py
- storyscript/App.py
- storyscript/Bundle.py
- tests/unittests/Api.py
- tests/unittests/App.py
- tests/unittests/Bundle.py
Closes #396.
- added the possibility to fallback to `string` files in `Bundle`
- add `loadm` to the public API for loading multiple stories from memory
Add `loadm` to the API for compiling stories from a map.
---
I'm still inexperienced with Storyscript, so please review with care.
Also, I went with a very naive approach of falling back to string files in the `Bundle`. Better ideas are welcome!
> feat(api): add ability to compile stories from a map

- storyscript/ErrorCodes.py
- storyscript/compiler/Compiler.py
- storyscript/parser/Grammar.py
- tests/integration/compiler/Assignments.py
- tests/integration/compiler/Compiler.py
- tests/integration/parser/Parser.py
- tests/unittests/ErrorCodes.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/parser/Grammar.py
closes #239
Implement chains of mutation using `then` as connector. Both inline and nested syntaxes are supported. Here's an example:
```coffee
message = ['merry', 'christmas'] join separator:' '
then uppercase only:1
then format template:'{}!'
```
> Mutations chains

- storyscript/Story.py
- tests/integration/Story.py
- tests/unittests/Story.py
Fixes #451
Every match in multiline comments is now further passed through `re.sub` and all lines are cleared (replaced with blank lines)
The function handling inline comments (`remove_comments`) already ignores `\n` while finding a match to clear
It should work if you compile a story:
```
$ cat test.story
###
abc
###
a=1 ###
a comment
###
z=1 # abc
###
abc
def
ghi
###
zzz = 11$ # <-- error
$ storyscript compile test.story
Error: syntax error in story at line 16, column 9
16|    zzz = 11$ 
```
Fix bug: comments alter the line number
> fix(story): comments don't alter the line number

- setup.py
- storyscript/Cli.py
- tests/unittests/Cli.py
Closes https://github.com/storyscript/storyscript/issues/419
- Added aliases for all the CLI commands 
- Added alias for `--version` as `-v`
- Added tests for all the aliases
- Added `click-alias` as dependency to `setup.py`
- I used the `ClickAliasedGroup` class from `click-alias`
- Try to run commands such as `storyscript h` for help 
```
$ storyscript h
Usage: storyscript [OPTIONS] COMMAND [ARGS]...
Learn more at http://storyscript.org
Options:
-v, --version  Prints Storyscript version
--help         Show this message and exit.
Commands:
compile (c)
grammar (g)
help (h)
lex (l)
new (n)
parse (p)
version (v)
```
Feature: Added aliases for CLI commands
> feat(cli): add aliases for all commands

- storyscript/exceptions/StoryError.py
- tests/integration/Exceptions.py
- tests/unittests/exceptions/StoryError.py
Closes https://github.com/storyscript/storyscript/issues/462
- renamed `error_code` to `error_tuple` as it is a better name, containing both the error code and hint.
- added a new `error_code` function to extract error code from `error_tuple`
- changed the format string to print the code with the message.
- Changed and Added tests to reflect changes
As mentioned in the original issue.
Feature: Errors now print error code as well as hint.
> feat(exceptions): return error code with message 

- storyscript/Api.py
- storyscript/App.py
- storyscript/Bundle.py
- storyscript/Cli.py
- storyscript/ErrorCodes.py
- storyscript/Story.py
- storyscript/compiler/Objects.py
- storyscript/exceptions/CompilerError.py
- storyscript/exceptions/StoryError.py
- storyscript/parser/Parser.py
- storyscript/parser/Tree.py
- tests/integration/Api.py
- tests/integration/Cli.py
- tests/integration/Exceptions.py
- tests/unittests/Api.py
- tests/unittests/App.py
- tests/unittests/Bundle.py
- tests/unittests/Cli.py
- tests/unittests/ErrorCodes.py
- tests/unittests/Story.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Objects.py
- tests/unittests/exceptions/CompilerError.py
- tests/unittests/exceptions/StoryError.py
- tests/unittests/parser/Tree.py
Fixes https://github.com/storyscript/storyscript/issues/449
- StoryError no longer exists directly in Story
- Passing `debug` around everywhere is superfluous with this change
- The CLI simply catches the StoryError and is itself in charge of error handling (this is also nice because the CLI class knows whether coloring should be used, sth. the error shouldn't need to know)
- On any error, the compiler now exits with a non-zero exit code (see also: https://en.wikipedia.org/wiki/Exit_status#POSIX).
- For better testing, `SyntaxError` now already supports omitting the coloring (this should be refactored as part of #458 though)
- Errors now are caught and rethrown as `StoryError`s 
- `SyntaxError` gained a `short_message` message which can be used for short one-line messages …
> fix(compiler) - Compile code inside a try block

- storyscript/ErrorCodes.py
- storyscript/exceptions/StoryError.py
- tests/integration/Exceptions.py
- tests/unittests/exceptions/StoryError.py
Fixes https://github.com/storyscript/storyscript/issues/372
**What I did**
- Added E0041 as generic, formattable error message for invalid tokens
**Example**
```coffee
x = $
```
Before:
```
Error: syntax error in 372.story at line 1, column 6
1|    x = 3$
^
```
Now:
```
Error: syntax error in story at line 1, column 5
1|    x = $
^
E0041: `$` is not allowed here
```
Note that  when we can detect no intention here, displaying the `invalid_token` message is always correct as the parser didn't allow the token here and we're just translating the Lark exception. It's also a bit better than an unidentified error.
(this needs https://github.com/storyscript/storyscript/pull/473 which is why ca389f1 is included here too).
> Assignment errors

- storyscript/exceptions/StoryError.py
- tests/unittests/exceptions/StoryError.py
Only use `self.error.message` when the occurred error has a message function and soft-fallback to `str`.
> fix(compiler): fix the hint message generation for unidentified errors

- storyscript/parser/Grammar.py
tl;dr: it's a statement - [no need for the five question marks](https://github.com/storyscript/storyscript/blame/master/storyscript/parser/Grammar.py#L113).
Statement: https://en.wikipedia.org/wiki/Statement_(computer_science)
> A program written in such a language is formed by a sequence of one or more statements. A statement may have internal components (e.g., expressions).
Also note that your blocks are typically called compound statements.
In other words: it can only span a single line (like `imports` or `assignments`), "blocks" (aka compound statements) can span multiple statements (lines).
> chore(grammar): Remove comments about the raise_statement

- storyscript/parser/Transformer.py
- storyscript/parser/Tree.py
- tests/integration/Api.py
- tests/integration/compiler/Compiler.py
- tests/unittests/parser/Transformer.py
- tests/unittests/parser/Tree.py
Fixes https://github.com/storyscript/storyscript/issues/377
- Added a transformer for zero-argument function calls (as `absolute_expression`) to `service`s
Functions and services without arguments can now be called.
> feat(compiler): allow function calls with zero arguments

- storyscript/compiler/Objects.py
- tests/unittests/compiler/Objects.py
- Changed the string regex to ignore `{` and `}` if they are preceded by `\`
Check the tree with the following story
```
a = "{this} is a variable \{that\} is not"
```
The tree will consider `this` as a variable and `that` as not.
feat(compiler): made escaping curly braces possible
Closes https://github.com/storyscript/storyscript/issues/442
> feat(compiler): allow escaping curly braces in strings

- storyscript/compiler/Preprocessor.py
- tests/unittests/compiler/Preprocessor.py
Refactored the Preprocessor into an understandable visitor as it was super-hard to debug it while I was working on introducing complex expressions everywhere (https://github.com/storyscript/storyscript/issues/420). 
Motivation:
- it already reduces the code size
```
1 file changed, 34 insertions(+), 74 deletions(-)
```
- this will make it easier to understand the preprocessor (only one behavior now)
- this will make it a lot easier to add new language constructs that use `inline_expression` (i.e. no changes necessary)
- this is faster than iterating over the entire tree multiple times with `find_data` (and the out-of-box iteration in LARK is slow too, which they admit themselves: https://github.com/lark-parser/lark/blob/8cc53379ec498f7d70a45a23a604b36537ac94f6/lark/tree.py …
> refactor(preprocessor): transform the preprocessor into a generic visitor

- storyscript/App.py
- storyscript/Cli.py
- tests/unittests/App.py
- tests/unittests/Cli.py
Closes https://github.com/storyscript/storyscript/issues/505
Just applied the diff from https://github.com/storyscript/storyscript/issues/505, propagated to App and added tests.
I was needing this for two PRs now (the preprocessor is tricky), so instead of applying my diff every time, it, it's not too much work to get this in master.
`--preprocess` has been added to `storyscript parse`, which allows to run the preprocessor on the AST as well. A similar flag has been ade
> feat(CLI): allow optional preprocessing of the AST

- storyscript/ErrorCodes.py
- storyscript/compiler/Compiler.py
- storyscript/exceptions/CompilerError.py
- storyscript/exceptions/StoryError.py
- tests/integration/Exceptions.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/exceptions/CompilerError.py
- tests/unittests/exceptions/StoryError.py
Fixes https://github.com/storyscript/storyscript/issues/508
- added support for storing extra arguments in the CompilerError
- check whether a function has already been declared (and yield a CompilerError)
```coffee
function foo
return 1
function foo
return 2
```
```
Error: syntax error in story at line 4, column 10
4|    function foo
^^^
E0042: `foo` has already been declared at line 1
```
Function can't be redeclared within the same story. Previously they would silently overwrite their previous declaration, now the Compiler will throw an Error.
> Fix: Do not allow function redeclaring

- setup.py
Currently master is failing because a new version of lark breaks a few tests in Storyscript. I will go ahead and merge this for now, s.t. master is green and we can take more time to look into the failures when we decide to upgrade Lark.
Locked the version of Lark to 0.6.5.
> Lock the version of Lark to 0.6.5

- storyscript/compiler/Faketree.py
- storyscript/compiler/Lines.py
- tests/unittests/compiler/Faketree.py
- tests/unittests/compiler/Lines.py
Closes https://github.com/storyscript/storyscript/issues/504
- generate non-random path (based on the line number), e.g. `p-42`
- generate non-random fake line numbers (based on the original_line + number of insertions), e.g. `1.0.0`
- adjust sorting in `Lines` to sort the stable fake line-numbers correctly
- changed `new_lines` to a dict as its only used for `get_line` and now the lookup is in `O(log n)` and not in `O(n)`
- there can only be one name set per fake line number (aka statement) as it's a top-level attribute, thus we can use the line number
- the fake line number was more difficult to get done nicely as `Lines` still constantly resorts the existing lines, but the trick here is to (1) split by the parts (s.t. inserted lines will always be …
> Fix: The compiler should create reproducible builds

- storyscript/ErrorCodes.py
- storyscript/compiler/Compiler.py
- storyscript/parser/Grammar.py
- tests/integration/compiler/Compiler.py
- tests/unittests/ErrorCodes.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/parser/Grammar.py
closes #391
Added `break` to the syntax and the `break_outside` error for when a break is outside of a block
> Add syntax for break

- .circleci/config.yml
- .coveragerc
- storyscript/compiler/Objects.py
- storyscript/exceptions/InternalCompilerError.py
- storyscript/exceptions/__init__.py
- tests/unittests/exceptions/InternalCompilerError.py
Found this one while debugging the Compiler. Explicitness would have helped quite a bit here.
Made sure that no unhandled types are getting passed to `values` and get silently swollen.
> refactor(Compiler): be explicit about handling of 'null'

- storyscript/Story.py
- storyscript/parser/Grammar.py
- tests/integration/Api.py
- tests/integration/compiler/Compiler.py
- tests/unittests/Story.py
- tests/unittests/parser/Grammar.py
Fixes https://github.com/storyscript/storyscript/issues/535
- allowed files without any statements (aka no blocks)
- changed `Story` to call `clean_source` while it's constructed as e.g. the API caller forgot to call it before
Files without any statements are now valid.
> Fix #535 - Files with comments only cause unexpected exception

- storyscript/compiler/Compiler.py
- storyscript/compiler/Objects.py
- storyscript/parser/Grammar.py
- tests/integration/compiler/Compiler.py
- tests/integration/parser/Parser.py
- tests/integration/parser/Values.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Objects.py
- tests/unittests/parser/Grammar.py
Closes https://github.com/storyscript/storyscript/issues/501
- Modified the Grammar to allow plus/minus sign directly with numbers (now `-2` is the actual value, and it's no longer a lost `-` child somewhere up the tree)
- Added integration tests for the compiler
- Modified the Compiler to allow unary expressions in global/absolute_expressions, e.g. `2` triggered an error until, but `2 + 2` was ok.
- Negative signs are no longer dropped from numeric values
- Numbers are now valid global expressions
>  fix(parse): allow numbers and floats with a plus/minus sign

- storyscript/ErrorCodes.py
- tests/unittests/ErrorCodes.py
Introduced in https://github.com/storyscript/storyscript/pull/531.
On of the reasons why peer-review is a good idea.
> fix(Compiler): error codes should be four digits long

- tests/integration/compiler/Compiler.py
Fixes https://github.com/storyscript/storyscript/issues/433
Added a test for https://github.com/storyscript/storyscript/issues/433
https://github.com/storyscript/storyscript/pull/542 already did the hard work to fix this.
- Exponential expressions are no longer unnecessarily nested
> fix(compiler): do not nest exponential expressions unnecessarily

- storyscript/compiler/Compiler.py
- storyscript/parser/Grammar.py
- tests/integration/Exceptions.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/parser/Grammar.py
closes #544
`return` can now be used without an `entity` and can be used to exit a block. 
- `return` is no longer ignored in the tree
> Return block exit

- storyscript/ErrorCodes.py
- storyscript/exceptions/StoryError.py
- tests/integration/Exceptions.py
- tests/unittests/exceptions/StoryError.py
Fixes https://github.com/storyscript/storyscript/issues/485
A more helpful error message is now triggered when a block is required and none is provided (e.g. after `while true`)
> feat(storyerror): return a better error message when a block should start

- storyscript/compiler/Compiler.py
- tests/integration/compiler/Compiler.py
Fixes https://github.com/storyscript/storyscript/issues/575
- The problem was that `self.lines.variables` looks like `[['a']]` as at some point `name` must have been changed to an array and not a single string anymore
Mutation assignments are now compiled correctly
> fix(compiler): compile mutation assignments correctly

- storyscript/compiler/Objects.py
- storyscript/parser/Grammar.py
- tests/integration/compiler/Compiler.py
- tests/integration/parser/Parser.py
- tests/unittests/compiler/Objects.py
- tests/unittests/parser/Grammar.py
Fixes https://github.com/storyscript/storyscript/issues/560
Service, mutation and function arguments now accept arbitrary expressions.
> feat(compiler): allow expression in service, mutation and function arguments

- storyscript/parser/Grammar.py
- tests/integration/compiler/Compiler.py
- tests/unittests/parser/Grammar.py
Fixes https://github.com/storyscript/storyscript/issues/580
Note that `a-b` and `a/b` are currently valid entity names:
```
NAME.1: /[a-zA-Z-\/_0-9]+/
```
I will open a separate issue for this.
- Adjusted the operator priority for `+`, `-` and `%`, s.t. Lark will prefer to parse them
- Added a long set of integration tests to prevent further issues
- Fix: Arithmetic expressions are no longer white-space sensitive
> fix(compiler): arithmetic expressions shouldn't be whitespace sensitive

- storyscript/compiler/Compiler.py
- storyscript/parser/Grammar.py
- tests/integration/compiler/Compiler.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/parser/Grammar.py
Fixes https://github.com/storyscript/storyscript/issues/568
- `return` now accepts an arbitrary expression
```coffee
function name key:int
return 2 + 2
```
now compiles
```json
{
"stories": {
"foo.story": {
"tree": {
"1": {
"method": "function",
"ln": "1",
"output": [],
"name": null,
"service": null,
"command": null,
"function": "name",
"args": [
{
"$OBJECT": "argument",
"name": "key",
"argument": {
"$OBJECT": "type",
"type": "int"
}
}
],
"enter": "2",
"exit": null,
"parent": null,
"next": "2"
},
"2": {
"method": "return",
"ln": "2",
"output": null,
"name": null,
"service": null,
"command": null,
"function": null,
"args": [
{
"$OBJECT": "expression",
"expression": "sum",
"values": [
2,
2
]
}
],
"enter": null,
"exit": null,
"parent": "1"
}
}, …
```
> feat(compiler): allow arbitrary expressions for return

- storyscript/compiler/Objects.py
- tests/unittests/compiler/Objects.py
closes #594 
Fix mutations having only their first argument compiled, by calling Objects.arguments with the correct tree
> Missing arguments in mutations

- storyscript/compiler/Objects.py
- storyscript/parser/Grammar.py
- tests/integration/compiler/Compiler.py
- tests/unittests/compiler/Objects.py
- tests/unittests/parser/Grammar.py
Fixes https://github.com/storyscript/storyscript/issues/519
- This was already implemented in the Grammar part (and most of the Compiler in https://github.com/storyscript/storyscript/pull/542) which is why this PR is so small
- However, I added quite a bunch of integration tests to hopefully avoid future breakages
```coffee
a = not b
```
```json
{
"stories": {
"foo.story": {
"tree": {
"1": {
"method": "expression",
"ln": "1",
"output": null,
"name": [
"a"
],
"service": null,
"command": null,
"function": null,
"args": [
{
"$OBJECT": "expression",
"expression": "not",
"values": [
{
"$OBJECT": "path",
"paths": [
"b"
]
}
]
}
],
"enter": null,
"exit": null,
"parent": null
}
},
"services": [],
"entrypoint": "1",
"modules": {},
"functions": {}, …
```
> feat(compiler): implement the unary operator '!'

- storyscript/parser/Grammar.py
- tests/integration/compiler/Assignments.py
- tests/integration/parser/Parser.py
- tests/unittests/parser/Grammar.py
Fixes https://github.com/storyscript/storyscript/issues/558 and https://github.com/storyscript/storyscript/issues/557
- Used a RegExp that allows escaping of the same quotes
- Added integration tests
- Fix: string escaping for the respective quotes works now
> fix(grammar): allow string escaping for quotes

- storyscript/compiler/Compiler.py
- storyscript/compiler/Lines.py
- storyscript/compiler/Preprocessor.py
- tests/integration/compiler/Compiler.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Lines.py
- tests/unittests/compiler/Preprocessor.py
Fixes #604 and #605 
- when service_fragment are split up into fake lines -> we need to convert them into a mutation fragment
- when a service_fragment is called, we need to check whether the variable has been defined before (this check didn't work because `self.variables` wasn't always set)
I am not very happy with the Preprocessor and we should probably have a more detailed look at it in the near future.
- Fix: services and mutations can be used together
> Allow mutation and services to be used together

- storyscript/Version.py
- tests/unittests/Version.py
Fix https://github.com/storyscript/storyscript/issues/616
- fix(version): pipe stderr to /dev/null
- feat(version): cache read_version to avoid superfluous reads
- feat(version): try the common case (read_version) first
> Try read_version first + cache it + use stderr for git API calls

- storyscript/compiler/Faketree.py
- storyscript/compiler/Preprocessor.py
- tests/e2e/when_enter_line_fake_assignment.json
- tests/e2e/when_enter_line_fake_assignment.story
- tests/unittests/compiler/Faketree.py
- tests/unittests/compiler/Preprocessor.py
Closes https://github.com/storyscript/storyscript/issues/615
The problem was that in the Preprocessor we "fixup" the line of the fake path reference to the original line. However, with this fixup we overwrote the "path" path of the inserted fake node too.
This PR refactors the Preprocessor and FakeTree a bit, s.t. a proper copy is returned
> fix(preprocessor): make a copy of the returned path reference and fixup the line numbers directly

- .circleci/config.yml
From https://circleci.com/gh/storyscript/storyscript/679
> chore(circleci): install twine on the deploy job

- .circleci/config.yml
It looks like the `setuptools` version on CircleCi is simply too old.
(see e.g. https://circleci.com/gh/storyscript/storyscript/683)
> chore(CircleCI): Bump Python to 3.6.8 on CircleCi

- .circleci/config.yml
- setup.py
Fixes https://github.com/storyscript/storyscript/issues/616
The problem that @judepereira observed was due to an egg automatically created out of the source archive and this binary egg not containing a `VERSION` file.
> fix(pip): provide a custom BDist step

- storyscript/Version.py
- tests/unittests/Version.py
- Removed the LRU caching as it doesn't work with exceptions in favor of a simple `_version`
- Try to read the `VERSION` string from the disk first
> chore(setup): make the VERSION reading more full-proof

- storyscript/ErrorCodes.py
- storyscript/compiler/Compiler.py
- storyscript/parser/Grammar.py
- storyscript/parser/Transformer.py
- tests/integration/compiler/Compiler.py
- tests/integration/parser/Parser.py
- tests/unittests/ErrorCodes.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/parser/Grammar.py
- tests/unittests/parser/Transformer.py
Closes #595
* Renamed all definitions related to the 'raise' keyword to 'throw'. Edited tests consequently.
* 'raise' is deprecated in favour of 'throw'
> replace 'raise' in favour of 'throw'

- storyscript/compiler/Compiler.py
- storyscript/compiler/Lines.py
- tests/e2e/complex_assert.json
- tests/e2e/exit_line.json
- tests/e2e/exit_line_complex.json
- tests/e2e/exit_line_complex.story
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Lines.py
A better fix to https://github.com/storyscript/storyscript/issues/635
- Keep track of the currently entered scopes
- When appending a new line, set the `exit` value of all previously opened, but not closed scopes to this new line
- Keep the old logic which special cases this for e.g. `else` or `elseif`
> fix(Compiler): set 'exit' correctly for blocks

- .circleci/config.yml
- .coveragerc
- storyscript/compiler/Compiler.py
- storyscript/parser/Grammar.py
- storyscript/parser/Indenter.py
- storyscript/parser/Transformer.py
- tests/e2e/multi_line_function_arguments.json
- tests/e2e/multi_line_function_arguments.story
- tests/e2e/multi_line_function_arguments2.error
- tests/e2e/multi_line_function_arguments2.story
- tests/e2e/multi_line_function_arguments3.error
- tests/e2e/multi_line_function_arguments3.story
- tests/e2e/runner.py
- tests/integration/Exceptions.py
- tests/integration/parser/Indenter.py
- tests/unittests/parser/Grammar.py
- tests/unittests/parser/Indenter.py
- tests/unittests/parser/Transformer.py
- tox.ini
Fixes https://github.com/storyscript/storyscript/issues/256
I had to modify the default indention logic from Lark and I went with choosing to emit a special `_DOUBLE_DEDENT` token (and reset the `indent_level`) if we haven't hit the parent with an indention yet. I preferred this special token over just an `_INDENT` as this is a lot more unique and we thus automatically forbid cases where the function arguments have the same indentation as the nested block.
Think:
```coffee
function name key:int
key2:string
a = 0
```
Which in case we would just emit a fresh `_INDENT` would just be sth. like:
```
0 FUNCTION_TYPE function
1 NAME name
2 NAME key
3 _COLON :
4 INT_TYPE int
5 _NL 
6 _INDENT 			
7 NAME key2
8 _COLON :
9 STRING_TYPE string
10 _DEDENT 	
11 _INDENT 	
12 NAME a
13 …
```
> feat(Compiler): support multi-line function arguments

- storyscript/__main__.py
- tests/e2e/update
Fixes https://github.com/storyscript/storyscript/issues/425
- Added the ad-hoc `e2e` update tool which I'm currently using to the tree
- Allowed running storyscript on the CLI with `python -m storyscript`
- A few lines of bash for nice test automation (if this is used by anyone else, we can always convert it to Python)
```
./update <story-file|all>
<file>:  updates or creates the e2e output of a story
all:     updates all stories in parallel
Usage examples
--------------
> ./update all
(updates all story outputs in parallel)
> ./update function_call_nested.story
(creates or updates 'function_call_nested.json')
> ./update function_call_no_inline_expression.story
(creates or updates 'function_call_no_inline_expression.error')
``` …
> feat(tests): add a convenient and fast e2e update tool

- storyscript/ErrorCodes.py
- storyscript/Story.py
- storyscript/compiler/Compiler.py
- storyscript/compiler/Objects.py
- storyscript/exceptions/CompilerError.py
- storyscript/exceptions/ProcessingError.py
- storyscript/exceptions/StoryError.py
- storyscript/parser/Transformer.py
- storyscript/parser/Tree.py
- tests/integration/Cli.py
- tests/integration/Exceptions.py
- tests/unittests/Cli.py
- tests/unittests/ErrorCodes.py
- tests/unittests/Story.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/exceptions/CompilerError.py
- tests/unittests/exceptions/ProcessingError.py
- tests/unittests/exceptions/StoryError.py
- tests/unittests/parser/Transformer.py
- tests/unittests/parser/Tree.py
Required for e.g. https://github.com/storyscript/storyscript/pull/643
- ProcessingErrors now contain a `format` object (for parameters in their format string)
- Replaced the duplication in ` reserved_keyword_*` with a generic error (as format parameters are now supported)
> refactor(exceptions): attach formats to thrown exceptions

- storyscript/exceptions/StoryError.py
- tests/unittests/exceptions/StoryError.py
Required by https://github.com/storyscript/storyscript/pull/643
As the `FakeTree` preprocessor inserts its fake lines, we might run into exceptions with these fake lines. However, the current logic can't handle fake lines and will always try e.g. `1.2.3` as line number. This PR fixes this, though we should move away from these fake lines long-term.
- Error line handling fixed for nested expressions
>  fix(exceptions): fix line handling with FakeTree lines

- storyscript/compiler/Faketree.py
- storyscript/parser/Tree.py
- tests/e2e/function_call_three_inline_exprs.json
- tests/e2e/function_call_three_inline_exprs.story
- tests/unittests/compiler/Faketree.py
- tests/unittests/parser/Tree.py
Fixes https://github.com/storyscript/storyscript/issues/648
- added `first_child` and `last_child` for better access safety
- fixed the FakeTree insertion for three or more fake insertions
>  fix(FakeTree): don't swallow real_line on three or more assignments

- storyscript/ErrorCodes.py
- storyscript/compiler/Compiler.py
- tests/e2e/call_function_expression_nested.json
- tests/e2e/call_function_expression_nested.story
- tests/e2e/call_function_expression_unary_complex_4.json
- tests/e2e/call_function_expression_unary_complex_4.story
- tests/e2e/expression_is_if_statement.json
- tests/e2e/expression_is_if_statement.story
- tests/e2e/service_call_require_command.error
- tests/e2e/service_call_require_command.story
- tests/e2e/while_with_mutation.json
- tests/e2e/while_with_mutation.story
- tests/integration/compiler/Compiler.py
From https://github.com/storyscript/storyscript/issues/275#issuecomment-464672501
>>> path arguments exists because services can be called without a command, as long as they have at least one argument:
>> IMHO we should remove path arguments, because an action is required to be able to execute anything.
> Yes, there is no need for path arguments
- Added a check & error message for service calls without a command
> feat(Compiler): require service calls to have command names

- storyscript/compiler/Objects.py
- tests/e2e/templated_strings.json
- tests/e2e/templated_strings.story
- tests/integration/compiler/Assignments.py
- tests/unittests/compiler/Objects.py
Fixes https://github.com/storyscript/storyscript/issues/608
- Lowered string templates into string concatenation
Example:
```coffee
t1 = "hello{story}world"
```
```json
{
"1": {
"method": "set",
"ln": "1",
"output": null,
"name": [
"t1"
],
"service": null,
"command": null,
"function": null,
"args": [
{
"$OBJECT": "expression",
"expression": "sum",
"values": [
{
"$OBJECT": "string",
"string": "hello"
},
{
"$OBJECT": "path",
"paths": [
"story"
]
},
{
"$OBJECT": "string",
"string": "world"
}
]
}
],
"enter": null,
"exit": null,
"parent": null
}
}
```
See the diff for more examples.
> feat(compiler): lower string templates as concatenation

- storyscript/App.py
- storyscript/Bundle.py
- storyscript/Story.py
- storyscript/compiler/Compiler.py
- storyscript/compiler/Preprocessor.py
- storyscript/parser/Parser.py
- tests/unittests/App.py
- tests/unittests/Bundle.py
- tests/unittests/Story.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Preprocessor.py
- tests/unittests/parser/Parser.py
Required for https://github.com/storyscript/storyscript/pull/678, fixes https://github.com/storyscript/storyscript/issues/685
Creating the parser (i.e. building the EBNF grammar and parsing it by Lark) is very expensive. This should only be done once. This PR moves creating the instance of `parser` up in the call tree and saves an instances of the `parser` in the root node of the tree for easy access by the compiler.
> refactor(Parser): don't recreate instances of the parser

- storyscript/compiler/Compiler.py
- storyscript/compiler/Lines.py
- tests/unittests/compiler/Compiler.py
- tests/unittests/compiler/Lines.py
Fixes https://github.com/storyscript/storyscript/issues/658
Lines are not longer constantly resorted. This is good for performance, reduced complexity and also required for https://github.com/storyscript/storyscript/issues/688
> refactor(compiler): Remove sorting in Lines

- .circleci/config.yml
- storyscript/Bundle.py
- storyscript/Story.py
- storyscript/parser/Indenter.py
- tests/integration/Api.py
- tests/integration/compiler/Assignments.py
- tests/integration/compiler/Compiler.py
- tests/integration/compiler/Functions.py
- tests/integration/conftest.py
- tests/integration/parser/Parser.py
- tests/integration/parser/Values.py
- tests/unittests/Bundle.py
- tests/unittests/Story.py
This should greatly improve the runtime of the tests as creation the parser takes about 0.3-0.6s and we currently do this for __every__ integration test.
See also: https://github.com/storyscript/storyscript/issues/685
> feat(parser): cache the instance of the Storyscript parser

- storyscript/parser/Transformer.py
- tests/unittests/parser/Transformer.py
A first step towards fixing https://github.com/storyscript/storyscript/issues/728
> fix(transformer): return nested block for multi-line indented function arguments

- storyscript/exceptions/StoryError.py
- tests/e2e/multi_line_function_arguments2.error
- tests/e2e/semantics/foreach_dict_key_float.error
- tests/e2e/semantics/foreach_dict_key_int.error
- tests/e2e/semantics/foreach_invalid6.error
- tests/e2e/semantics/foreach_invalid7.error
- tests/e2e/semantics/return_null.error
- tests/e2e/semantics/service_block_output_invalid.error
- tests/e2e/semantics/when_output_invalid.error
- tests/e2e/semantics/when_output_invalid2.error
- tests/e2e/tab_error.error
- tests/e2e/tab_error.story
- tests/e2e/tab_error2.error
- tests/e2e/tab_error2.story
- tests/unittests/exceptions/StoryError.py
Fixes https://github.com/storyscript/storyscript/issues/573
Not super happy with this yet, but it does fix the issue.
The problem here is that tabs will align to the nearest tab unit and with the preceding spaces this happens:
In other words the `tab` is only one real space long. Moreover, for the location of the start and endcolumn, the tab character was counted as a single character.
So this solution, replaces all tabs in the printed line and adjusts the start and end_column accordingly.
This works, but is rather ugly and requires us to select a tab to space conversion width.
> fix(exceptions): show correct column location with tabs

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/ExpressionResolver.py
- tests/e2e/inline_service_output.error
- tests/e2e/inline_service_output.story
- tests/e2e/inline_service_output2.error
- tests/e2e/inline_service_output2.story
- tests/e2e/inline_service_output3.error
- tests/e2e/inline_service_output3.story
- tests/e2e/inline_service_output4.error
- tests/e2e/inline_service_output4.story
Fixes #662 
Supersedes https://github.com/storyscript/storyscript/pull/717
> feat(compiler): don't allow 'as <output>' in service inline expressions

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/ReturnVisitor.py
- storyscript/exceptions/StoryError.py
- tests/e2e/call_function_expression_nested.json
- tests/e2e/call_function_expression_nested.story
- tests/e2e/call_function_expression_unary_complex_4.json
- tests/e2e/call_function_expression_unary_complex_4.story
- tests/e2e/function_invalid_return.error
- tests/e2e/function_invalid_return.story
- tests/e2e/function_return_mutation_without_type.error
- tests/e2e/function_return_mutation_without_type.story
- tests/e2e/function_return_service_without_type.error
- tests/e2e/function_return_service_without_type.story
- tests/e2e/function_without_return_returns_value.error
- tests/e2e/function_without_return_returns_value.story
- tests/e2e/function_without_return_returns_value2.error
- tests/e2e/function_without_return_returns_value2.story
- tests/e2e/return_complex_expression.json
- tests/e2e/return_complex_expression.story
- tests/e2e/return_complex_expression_2.json
- tests/e2e/return_complex_expression_2.story
- tests/e2e/return_with_mutation.json
- tests/e2e/return_with_service.json
- tests/e2e/time_type.json
- tests/e2e/time_type.story
- tests/integration/Exceptions.py
- tests/integration/compiler/Functions.py
Fixes https://github.com/storyscript/storyscript/issues/780
This is no longer allowed:
```coffee
function my_function
return 0
my_function ()
```
yields:
<details>
```json
Error: syntax error in story at line 2, column 9
2|      return 0
^
E0110: Function has no return output defined. Only `return` is allowed.
```
</details>
> feat(semantics): check function without return type for their returns

- storyscript/compiler/json/Objects.py
- tests/e2e/assignments_basic.json
- tests/e2e/regex_after_name5.json
- tests/e2e/regex_after_name6.json
- tests/e2e/semantics/mutation/string_contains_pattern.json
- tests/e2e/semantics/return_types.json
- tests/unittests/compiler/json/Objects.py
Example:
```coffee
r = str contains pattern: /llo/g
```
yields:
<details>
```json
{
"tree": {
"1": {
"method": "execute",
"ln": "1",
"name": [
"r"
],
"service": "str",
"command": "contains",
"args": [
{
"$OBJECT": "arg",
"name": "pattern",
"arg": {
"$OBJECT": "regexp",
"regexp": "llo",
"flags": "g"
}
}
],
"src": "r = str contains pattern: /llo/g"
}
},
"services": [
"str"
],
"entrypoint": "1",
"version": "0.17.0-3-gde20ad9"
}
```
</details>
> fix(Objects): don't emit / for regexp objects

- storyscript/Api.py
- tests/e2e/runner.py
- tests/e2e/update
- tests/integration/Api.py
- tests/integration/compiler/Compiler.py
- tests/integration/compiler/Functions.py
- tests/integration/compiler/semantics/types/Types.py
- tests/integration/compiler/semantics/types/TypesOperations.py
- tests/unittests/Api.py
This changes the public Storyscript API to return a `StoryscriptCompilationResult` instead of the story result.
This means that the API no longer will throw an exception, but return an object will a list of `errors` and the `result`. In the future, this object will contain a list of warnings and deprecations, too.
> refactor(API): improve interface to support multiple error messages in the future

- storyscript/compiler/json/Objects.py
- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/parser/Grammar.py
- tests/e2e/semantics/nested_types.json
- tests/integration/parser/Values.py
- tests/integration/parser/grammar.lark
- tests/unittests/compiler/json/Objects.py
It's a `map` and soon we're introducing the actual `object` type.
> refactor(rename): objects to map

- setup.py
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
> Require Python 3.5 or newer

- storyscript/compiler/semantics/ExpressionResolver.py
- tests/e2e/mutation_expression.json
- tests/e2e/mutation_expression.story
- tests/e2e/service_name_minus.json
- tests/e2e/service_name_minus.story
- tests/e2e/service_name_slash.json
- tests/e2e/service_name_slash.story
Fixes https://github.com/storyscript/storyscript/issues/878
The problem here is that the compiler doesn't know whether it's a mutation or service call from the syntax alone, but must do semantic analysis on this.
> fix(semantics): avoid over-greedy mutation conversion

- storyscript/compiler/semantics/types/Types.py
Required for https://github.com/storyscript/storyscript/pull/890 as this allows to receive the actual type of a compare or equal operation.
> refactor(semantics): return the resulting type from cmp/equal

- storyscript/exceptions/CompilerError.py
- storyscript/exceptions/ProcessingError.py
- storyscript/exceptions/StoryError.py
- storyscript/parser/Transformer.py
- storyscript/parser/Tree.py
- tests/unittests/exceptions/CompilerError.py
- tests/unittests/exceptions/StoryError.py
- tests/unittests/parser/Transformer.py
- tests/unittests/parser/Tree.py
This fixes problems in SLS that only manifest in some versions of Python.
See e.g. https://circleci.com/gh/storyscript/sls/29?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
tl;dr: it's best to not use named arguments that conflict with built-in Python functions.
> chore(python): fix conflicts with the built-in format function

- .circleci/config.yml
Fixes https://github.com/storyscript/storyscript/issues/897
> chore(releases): upload a binary wheel to PyPi too

- storyscript/parser/Grammar.py
- tests/e2e/function_call_indented.json
- tests/e2e/function_call_indented.story
- tests/integration/parser/grammar.lark
This fixes parts of https://github.com/storyscript/storyscript/issues/891, in particular:
```coffee
function fun a: string b:string returns string
return "foo"
fun(a: ""
b: ""
)
```
yields:
<details>
```json
{
"tree": {
"1": {
"method": "function",
"ln": "1",
"output": [
"string"
],
"function": "fun",
"args": [
{
"$OBJECT": "arg",
"name": "a",
"arg": {
"$OBJECT": "type",
"type": "string"
}
},
{
"$OBJECT": "arg",
"name": "b",
"arg": {
"$OBJECT": "type",
"type": "string"
}
}
],
"enter": "2",
"exit": "4.1",
"src": "function fun a: string b:string returns string",
"next": "2"
},
"2": {
"method": "return",
"ln": "2",
"args": [
{
"$OBJECT": "string",
"string": "foo"
}
],
"parent": "1",
"src": "\treturn \"foo\"",
"next": "4.1"
},
"4.1": {
"method": "call",
"ln": "4.1",
"name": [
"__p-4.1"
], …
```
> feat(parser): multi-line call expressions (partially)

- storyscript/compiler/semantics/TypeResolver.py
- storyscript/compiler/semantics/symbols/Scope.py
- storyscript/compiler/semantics/symbols/Symbols.py
- tests/e2e/semantics/head_const_output.json
- tests/e2e/semantics/head_const_output.story
- tests/e2e/semantics/head_const_output2.json
- tests/e2e/semantics/head_const_output2.story
- tests/e2e/semantics/head_const_output3.json
- tests/e2e/semantics/head_const_output3.story
- tests/e2e/semantics/head_const_output4.error
- tests/e2e/semantics/head_const_output4.story
- tests/e2e/semantics/head_const_output5.json
- tests/e2e/semantics/head_const_output5.story
- tests/e2e/semantics/head_const_output6.json
- tests/e2e/semantics/head_const_output6.story
- tests/e2e/semantics/head_const_output7.error
- tests/e2e/semantics/head_const_output7.story
- tests/e2e/semantics/head_const_output8.error
- tests/e2e/semantics/head_const_output8.story
- tests/e2e/semantics/head_const_output9.json
- tests/e2e/semantics/head_const_output9.story
- tests/e2e/service_event_output_readonly.error
- tests/e2e/service_output_readonly.error
- tests/e2e/service_output_readonly2.error
- tests/integration/compiler/semantics/types/Types.py
- tests/unittests/compiler/semantics/symbols/Symbols.py
Alternative fix for https://github.com/storyscript/storyscript/issues/926
See also: https://github.com/storyscript/storyscript/pull/927/files
```coffeescript
when client listen method:'post' path:'/foo' as res
v = res["foo"]
v["bar"] = ERROR
v = 2 # OK
```
> fix(semantics): make service output variable rebindable

- .circleci/config.yml
Fixes https://github.com/storyscript/storyscript/issues/967 as the code coverage workaround is no longer needed.
> chore(CI): remove code coverage workaround

- .circleci/config.yml
- setup.py
Due to the way setuptools.command.install.run handles detects
install command, sub classing Install breaks that login and thus
calling the `run` from super class results in a broken setup
process.
The setup process would finish without any errors but it won't
install the requirements specified in the setup.py which is not
expected. CI doesn't notice it because it uses `tox` to run tests
which installs dependacies itself.
In this change we try to reiterate the logic used in the super
class's defination of run and do the right thing for install
command and fallback to super class implmentation for the other
cases.
Fixes: #997
Try setting up a fresh virtual environment and setup new development environment. Before this PR dependencies won't be installed.
After this PR, …
> fix(setup.py): change how we handle install command

- storyscript/compiler/json/JSONExpressionVisitor.py
- storyscript/compiler/lowering/Faketree.py
- storyscript/compiler/lowering/Lowering.py
- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/parser/Grammar.py
- tests/e2e/explicit_cast_invalid.story
- tests/e2e/explicit_cast_invalid2.error
- tests/e2e/explicit_cast_invalid2.story
- tests/e2e/type_assignment.json
- tests/e2e/type_assignment.story
- tests/e2e/type_assignment_invalid.error
- tests/e2e/type_assignment_invalid.story
- tests/e2e/type_assignment_list_any.json
- tests/e2e/type_assignment_list_any.story
- tests/e2e/type_assignment_list_any2.json
- tests/e2e/type_assignment_list_any2.story
- tests/e2e/type_assignment_map_list.error
- tests/e2e/type_assignment_map_list.story
- tests/e2e/type_reassignment.json
- tests/e2e/type_reassignment.story
- tests/integration/parser/grammar.lark
This is done in order to make grammar coherant with the
storyscript theory of providing only one way of doing things.
int foo = "2" # Not accepted anymore.
foo = "2" as int # Acceptable.
Closes: #888.
Removed one of the two ways to type cast
Changed the grammar and removed possibility to lead assignment expression with a type.
Try running a story script with `int foo = "2"` type expressions.
It shouldn't be accepted.
> feat(grammar): stop accepting type assignment cast shorthand

- storyscript/parser/Parser.py
`Parser.parse` is used by external APIs which shouldn't need to worry about this flag.
> chore(Parser): make allow_single_quotes optional

- storyscript/compiler/semantics/functions/HubMutations.py
`maxRelDiff` and `maxAbsDiff` are now independently optional.
> Add approxEqual variants

- .circleci/config.yml
This is no longer needed as we do a proper `exclude` in `setup.py` now.
https://github.com/storyscript/storyscript/issues/1035
> chore(CI): don't remove tests directory on the CI

- setup.py
- storyscript/parser/Parser.py
- tests/e2e/invalid_return_type.error
- tests/e2e/invalid_return_type2.error
- tests/e2e/invalid_return_type5.error
- tests/e2e/multi_line_function_arguments3.error
- tests/integration/Exceptions.py
Closes https://github.com/storyscript/storyscript/issues/529
Unnecessarily depending on https://github.com/storyscript/storyscript/issues/529 .
WIP as the revised errors need to be carefully considered.  There is at least a significant change in the how the parser is processing and where it halts for these errors.  The previous errors were not very helpful for the user, and the revised error messages are even less helpful.
> Use Lark 0.7.1

- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/compiler/semantics/functions/Function.py
- tests/e2e/function_call_implicit_cast.json
- tests/e2e/function_call_implicit_cast.story
- tests/e2e/function_call_with_service_nested.json
- tests/e2e/mutation_expression.json
- tests/e2e/mutation_implicit_cast.json
- tests/e2e/mutation_implicit_cast.story
In this commit we start emitting type casts for the arguments in
function calls, mutations or services.
We were already doing the checks for arg compatibility and had
implicit cast method ready as well. In this commit we just refactor
the implicit_cast method a bit to extract out a type_cast_entity
function which works on single entity and add type casts to its AST
by adding as operator to its tree.
As a result, now calling a function which accpets a float parameter
with an int parameter will specifically emit a type cast
(as operator) in the AST.
Closes: #993.
> feat(semantics): emit type casts after doing arg type checks

- tests/e2e/bom16be_service.json
- tests/e2e/bom16le_service.json
- tests/e2e/bom8le_service.json
- tests/e2e/update
Required as https://github.com/storyscript/storyscript/pull/1040 used an old JSON output.
> chore(test): fix bom{8,16} tests files for newer testsuite

- tests/e2e/runner.py
To avoid any accidentally left-over files.
> chore(tests): check for .error/.json duplicates

- storyscript/compiler/semantics/ExpressionResolver.py
- tests/e2e/function_call_implicit_cast2.json
- tests/e2e/function_call_implicit_cast2.story
In this commit we fix the issue which arose due to the fact that
type_to_tree() didn't handle `any` type. This results in assertion
errors since give a type Map[string, any] this function can call
itself with type `any` and end up with errors.
In general as well, this function should have been able to handle
`any` type which we now add to it.
test case included.
Fixes: #1072.
> fix(ExpressionResolver): make type_to_tree() handle `any` type

- storyscript/compiler/semantics/TypeResolver.py
- tests/e2e/semantics/readonly_foreach.json
- tests/e2e/semantics/readonly_foreach.story
- tests/e2e/semantics/readonly_if.error
- tests/e2e/semantics/readonly_if.story
- tests/e2e/semantics/readonly_if2.error
- tests/e2e/semantics/readonly_if2.story
- tests/e2e/semantics/readonly_if3.error
- tests/e2e/semantics/readonly_if3.story
- tests/e2e/semantics/readonly_if4.error
- tests/e2e/semantics/readonly_if4.story
- tests/e2e/semantics/readonly_while.json
- tests/e2e/semantics/readonly_while.story
Fixes https://github.com/storyscript/storyscript/issues/1076, requires https://github.com/storyscript/storyscript/pull/1053 -> cherry-pick inhttps://github.com/storyscript/storyscript/pull/1081
if statements affect the parent scope if the symbol is defined in all statements, hence not looking at them here.
> fix(semantics): create a writable scope for foreach/while loops

- storyscript/ErrorCodes.py
- tests/e2e/continue_outside.error
- tests/integration/Exceptions.py
- tests/unittests/ErrorCodes.py
Change duplicate ErrorCode
Before:
```
tabs = (
'E0132',
'Tabs are not allowed.'
)
continue_outside = ('E0132', '`continue` is allowed only inside loops')
```
After:
```
tabs = (
'E0132',
'Tabs are not allowed.'
)
continue_outside = ('E0133', '`continue` is allowed only inside loops')
```
> fix(ErrorCodes): change duplicate use of error code to E0133

- storyscript/compiler/json/JSONCompiler.py
- storyscript/compiler/json/Lines.py
- storyscript/parser/Grammar.py
- tests/e2e/exit_line.json
- tests/e2e/pokemon_catch.json
- tests/e2e/pokemon_catch.story
- tests/e2e/scope_individual_try_catch.error
- tests/e2e/scope_individual_try_catch.json
- tests/e2e/try_catch.json
- tests/e2e/try_nested_throw_error.json
- tests/e2e/try_throw.json
- tests/e2e/try_throw_error.json
- tests/integration/parser/Parser.py
- tests/integration/parser/grammar.lark
- tests/unittests/compiler/json/Compiler.py
Fixes https://github.com/storyscript/storyscript/issues/1096
TODO:
> fix(grammar): allow pokematch catch

- setup.py
Releasing a new version of Storyscript got very easy, reducing the advantage of being able to release a patch of the Hub SDK.
As the Hub SDK contains the Hub builtins, imho for now it's a good idea to couple a Storyscript release with a specific version of the Hub SDK, s.t. it's easy to know which version of the Hub SDK was used by the user (only SS version required).
> Fix exact version of Hub SDK

- setup.py
To prevent e.g. https://circleci.com/gh/storyscript/runtime/1478
CC @judepereira
> Lock story-hub for 0.23 to 0.1.2

- tests/e2e/service_with_assignments.json
- tests/e2e/service_with_assignments.story
With this test case we wanna lock down any further regressions
in which assignments might get swallowed up by the service block.
The issue itself was fixed since it was first reported but a test case against it doesn't exist.
Closes: #620
> chore(tests): add test case for use of assignments in service_block

- storyscript/compiler/json/JSONCompiler.py
- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/compiler/semantics/TypeResolver.py
- storyscript/parser/Grammar.py
- storyscript/parser/Transformer.py
- tests/e2e/arg_name_shorthand3_error.error
- tests/e2e/arg_name_shorthand3_error.story
- tests/e2e/arg_name_shorthand7.json
- tests/e2e/arg_name_shorthand7.story
- tests/e2e/arg_name_shorthand8.json
- tests/e2e/arg_name_shorthand8.story
- tests/e2e/service_call_require_command.error
- tests/e2e/service_call_require_command2.error
- tests/e2e/service_call_require_command2.story
- tests/e2e/service_when_shorthand_arg.json
- tests/e2e/service_when_shorthand_arg.story
- tests/e2e/service_when_shorthand_arg_error.error
- tests/e2e/service_when_shorthand_arg_error.story
- tests/e2e/service_when_shorthand_arg_error2.error
- tests/e2e/service_when_shorthand_arg_error2.story
- tests/integration/parser/grammar.lark
Fixes https://github.com/storyscript/storyscript/issues/1114
TODO:
> feat(parser): allow argument shorthand syntax for the first service argument

- setup.py
- storyscript/Cli.py
click-alias is an unmaintained fork of click-aliases;
the latter is maintained by the click team, and
recently updated to support Click 7.
> feat(dependencies): Switch to click-aliases

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/ExpressionResolver.py
- storyscript/compiler/semantics/FunctionResolver.py
- storyscript/compiler/semantics/types/Types.py
- tests/e2e/function_return_app2.error
- tests/e2e/function_return_object.error
- tests/e2e/object_no_type_cast.error
- tests/e2e/object_no_type_cast.story
- tests/e2e/return_no_object.error
- tests/e2e/return_no_object.story
- tests/e2e/return_no_object2.error
- tests/e2e/return_no_object2.story
- tests/integration/compiler/semantics/types/Types.py
We aren't sure about what we want ObjectType to be. There is
confusion with Maps if we start calling {} to be an object?
Hence for the moment we decided to stop allowing objects
being returned from functions or other datatypes being
casted to an object. Well only datatype that can be casted
to an object is `any` so we ban that as well.
Fixes: #1200, #858
> feat(ObjectType): ban cast to object and return an object

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/TypeResolver.py
- tests/e2e/when_invalid_action.error
- tests/e2e/when_invalid_action.story
- tests/e2e/when_invalid_action1.error
- tests/e2e/when_invalid_action1.story
- tests/e2e/when_invalid_action2.error
- tests/e2e/when_invalid_action2.story
- tests/e2e/when_invalid_action3.error
- tests/e2e/when_invalid_action3.story
- tests/e2e/when_invalid_action4.error
- tests/e2e/when_invalid_action4.story
We make sure that:
* The event based action output in when block exists and
is the output of parent service block only in case when block is
nested inside a service block.
Eg.
```
a = 1
http server
when a listen path: "/" as r
r write content: "foobar"
```
Above errors out because `a` in when block isn't output of parent
service block.
```
http server
when client listen path: "/" as r
r write content: "foobar"
```
Above errors out because `client` in when block does not exist.
* For syntax like below:
```
a = http server
when a listen path: "/" as r
r write content: "foobar"
```
we make sure that `a` exists and is of type `object` and is wrapping
the output of the `Service`.
Fixes: #716
> check for existance of event based action output in when block

- README.md
This is because Pypi doesn't understand Github flavour markdown
emoji's and storyscript page appears on Pypi a bit broken.
To still keep the ease of understanding what a given emoji code
represents just by reading it, I added HTML comments after each
emoji code specifying its human readable name.
Emoji codes picked up from https://emojiguide.org/
Fixes: #1033
> chore(README.md): use unicode characters for emojis

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/ServiceTyping.py
- tests/e2e/expression_no_event.error
- tests/e2e/expression_no_event.story
- tests/e2e/expression_no_event2.error
- tests/e2e/expression_no_event2.story
This bans service actions which are event based from being used
as part of expressions.
eg.		`a = http server`
`(http server)`
The above lines is no longer allowed since `server` action is
event based.
**NOTE:**
This PR does the opposite of the issue #1050 and we are allowing this PR in for the moment. This is because we have decided to go along the direction of doing things in a way that allowing service assignments for event streaming won't require the runtime to change. This means we are going to  lower the such service assignments into service blocks so that for the runtime its bussines as usual. 
This is something which is sorta more involved project and isn't the highest priority right now so we are gonna defer it for later. As a result we need to for the moment ban such assignments …
> feat(ServiceTyping): ban event based services in expressions

- tests/e2e/update
This should have been fixed along with #1206 but wasn't so fixing
it now.
This doesn't require us to do any release immediately since its languages internal tooling but very easily it could have been the case. Sorry for the churn on this one.
> chore(tests/update): fix update tool post removal of StoryscriptHubFixture

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/ServiceTyping.py
- storyscript/compiler/semantics/TypeResolver.py
- tests/e2e/expression_no_event3.error
- tests/e2e/expression_no_event3.story
- tests/e2e/service_event_expected.error
- tests/e2e/service_event_expected.story
We add checks for services which are nested in nature and should
have event listeners to make sure they really do are using
event based actions
Fixes: #1212
> feat(ServiceTyping): check nested service blocks for events 

- setup.py
This allows dependents of Storyscript more freedom. They should still pin the versions of all dependencies for a release, s.t. each release is predictable.
> feat(setup.py): dependencies are no longer hard pinned

- MANIFEST.in
The sdist needs to have a LICENSE, and docs and tests
are used by packagers.
> chore(packaging): Add LICENSE, tests, etc to sdist

- storyscript/compiler/semantics/types/Types.py
- tests/e2e/object_assign_any.error
- tests/e2e/object_assign_any.story
- tests/e2e/object_assign_boolean.error
- tests/e2e/object_assign_boolean.story
- tests/e2e/object_assign_float.error
- tests/e2e/object_assign_float.story
- tests/e2e/object_assign_int.error
- tests/e2e/object_assign_int.story
- tests/e2e/object_assign_list.error
- tests/e2e/object_assign_list.story
- tests/e2e/object_assign_map.error
- tests/e2e/object_assign_map.story
- tests/e2e/object_assign_null.error
- tests/e2e/object_assign_null.story
- tests/e2e/object_assign_null2.error
- tests/e2e/object_assign_null2.story
- tests/e2e/object_assign_null3.error
- tests/e2e/object_assign_null3.story
- tests/e2e/object_assign_null4.error
- tests/e2e/object_assign_null4.story
- tests/e2e/object_assign_regexp.error
- tests/e2e/object_assign_regexp.story
- tests/e2e/object_assign_string.error
- tests/e2e/object_assign_string.story
- tests/e2e/object_assign_time.error
- tests/e2e/object_assign_time.story
First commit:
chore(Types): remove special case for AnyType
We can remove this since we migrated AnyType to behave like
unknown and hence any can no longer be assigned to anything
but any. Therefore AnyType.can_be_assigned will always return
None which the special case was added to do before the migration
of AnyType to behave like unknown.
Second commit:
feat(Types): prevent assigning null to objects
This one just adds the restriction with a few e2e tests.
Fixes: #1257
> feat(Types): prevent assigning null to objects

- storyscript/ErrorCodes.py
- storyscript/compiler/semantics/PathResolver.py
- storyscript/compiler/semantics/symbols/Symbols.py
- storyscript/compiler/semantics/types/Types.py
- tests/e2e/null_any.json
- tests/e2e/null_any.story
- tests/e2e/null_list_any.json
- tests/e2e/null_list_any.story
- tests/e2e/null_list_any2.json
- tests/e2e/null_list_any2.story
- tests/e2e/null_list_any3.error
- tests/e2e/null_list_any3.story
- tests/e2e/null_map.error
- tests/e2e/null_map.json
- tests/e2e/null_map_any.json
- tests/e2e/null_map_any.story
- tests/e2e/null_map_any2.json
- tests/e2e/null_map_any2.story
- tests/e2e/path_index_no_null.error
- tests/e2e/path_index_no_null.story
We make sure that `null` could be implicitly converted to `any`
so that it can be passed around in function arguments accepting
`any` as parameter.
Also I added another commit which prevents `null` being used in indexs. I believe we need this.
It stops things like
```
a = [1, 2]
a[null]
```
Fixes: #1276
> fix(Types): make null and any interoperability work

- storyscript/compiler/semantics/TypeResolver.py
- storyscript/compiler/semantics/types/Types.py
- tests/e2e/semantics/foreach_invalid2.error
- tests/e2e/semantics/foreach_invalid6.error
- tests/e2e/semantics/foreach_invalid6.story
- tests/e2e/semantics/foreach_invalid7.error
- tests/e2e/semantics/foreach_invalid7.story
- tests/e2e/semantics/foreach_no_any.error
- tests/e2e/semantics/foreach_no_any.story
We ban foreach to iterate over AnyType. In fact we only allow
it to iterate over MapType or ListType for the moment.
Fixes: #1300
> chore(TypeResolver): ban foreach to iterate over AnyType

- setup.py
* `io.open` is alias of in-built `open` we use the built-in one
* by default encoding is picked up from system so weird things
happen on Windows! We specify encoding to be 'utf-8' to avoid
that.
> fix(setup.py): fix issue with read on Windows

- .circleci/config.yml
- setup.py
- Python 3.8 is out
- Storyscript is only intended to be used via the Studio and the runtime only supports >=3.7
> chore(setup): bump minimal version of Python to 3.7

- tests/e2e/runner.py
- tests/e2e/utils/fixtures.py
- tests/integration/Api.py
Moving the fixture loading into a separate file isn't strictly necessary, but I thought it was loaded in another parts as well, so it's separated now.
> chore(tests): fix test suite for the newest hub SDK
